INSERT INTO `{prefix}gifts` (`name`, `key`, `icon_default`, `price`, `is_active`, `order`) VALUES
('Heart', 'heart', 'images/default/gift/heart.png', 10, 1, 1),
('Castle', 'castle', 'images/default/gift/castle.png', 20, 1, 2),
('Chocolate Box', 'chocolate_box', 'images/default/gift/chocolate-box.png', 30, 1, 3),
('Crown', 'crown', 'images/default/gift/crown.png', 40, 1, 4),
('Diamond Ring', 'diamond_ring', 'images/default/gift/diamond-ring.png', 50, 1, 5),
('Diamond', 'diamond', 'images/default/gift/diamond.png', 50, 1, 6),
('Fire', 'fire', 'images/default/gift/fire.png', 40, 1, 7),
('Fruits', 'fruits', 'images/default/gift/fruits.png', 30, 1, 8),
('Galaxy', 'galaxy', 'images/default/gift/galaxy.png', 20, 1, 9),
('Hug', 'hug', 'images/default/gift/hug.png', 10, 1, 10),
('Kiss Lips', 'kiss_lips', 'images/default/gift/kiss-lips.png', 20, 1, 11),
('Love Letter', 'love_letter', 'images/default/gift/love-letter.png', 30, 1, 12),
('Luxury Car', 'luxury_car', 'images/default/gift/luxury-car.png', 40, 1, 13),
('Music', 'music', 'images/default/gift/music.png', 50, 1, 14),
('Private Jet', 'private_jet', 'images/default/gift/private-jet.png', 60, 1, 15),
('Rose Flower', 'rose_flower', 'images/default/gift/rose-flower.png', 70, 1, 16),
('Teddy Bear', 'teddy_bear', 'images/default/gift/teddy-bear.png', 80, 1, 17),
('Turtle', 'turtle', 'images/default/gift/turtle.png', 90, 1, 18),
('Wine Glasses', 'wine_glasses', 'images/default/gift/wine-glasses.png', 100, 1, 19),
('Yacht', 'yacht', 'images/default/gift/yacht.png', 200, 1, 20);

INSERT INTO `{prefix}translations` (`table_name`, `column_name`, `foreign_key`, `locale`, `value`) VALUES
('gifts', 'name', (SELECT id FROM `{prefix}gifts` WHERE `key` = 'heart'), 'en', 'Heart'),
('gifts', 'name', (SELECT id FROM `{prefix}gifts` WHERE `key` = 'castle'), 'en', 'Castle'),
('gifts', 'name', (SELECT id FROM `{prefix}gifts` WHERE `key` = 'chocolate_box'), 'en', 'Chocolate Box'),
('gifts', 'name', (SELECT id FROM `{prefix}gifts` WHERE `key` = 'crown'), 'en', 'Crown'),
('gifts', 'name', (SELECT id FROM `{prefix}gifts` WHERE `key` = 'diamond_ring'), 'en', 'Diamond Ring'),
('gifts', 'name', (SELECT id FROM `{prefix}gifts` WHERE `key` = 'diamond'), 'en', 'Diamond'),
('gifts', 'name', (SELECT id FROM `{prefix}gifts` WHERE `key` = 'fire'), 'en', 'Fire'),
('gifts', 'name', (SELECT id FROM `{prefix}gifts` WHERE `key` = 'fruits'), 'en', 'Fruits'),
('gifts', 'name', (SELECT id FROM `{prefix}gifts` WHERE `key` = 'galaxy'), 'en', 'Galaxy'),
('gifts', 'name', (SELECT id FROM `{prefix}gifts` WHERE `key` = 'hug'), 'en', 'Hug'),
('gifts', 'name', (SELECT id FROM `{prefix}gifts` WHERE `key` = 'kiss_lips'), 'en', 'Kiss Lips'),
('gifts', 'name', (SELECT id FROM `{prefix}gifts` WHERE `key` = 'love_letter'), 'en', 'Love Letter'),
('gifts', 'name', (SELECT id FROM `{prefix}gifts` WHERE `key` = 'luxury_car'), 'en', 'Luxury Car'),
('gifts', 'name', (SELECT id FROM `{prefix}gifts` WHERE `key` = 'music'), 'en', 'Music'),
('gifts', 'name', (SELECT id FROM `{prefix}gifts` WHERE `key` = 'private_jet'), 'en', 'Private Jet'),
('gifts', 'name', (SELECT id FROM `{prefix}gifts` WHERE `key` = 'rose_flower'), 'en', 'Rose Flower'),
('gifts', 'name', (SELECT id FROM `{prefix}gifts` WHERE `key` = 'teddy_bear'), 'en', 'Teddy Bear'),
('gifts', 'name', (SELECT id FROM `{prefix}gifts` WHERE `key` = 'turtle'), 'en', 'Turtle'),
('gifts', 'name', (SELECT id FROM `{prefix}gifts` WHERE `key` = 'wine_glasses'), 'en', 'Wine Glasses'),
('gifts', 'name', (SELECT id FROM `{prefix}gifts` WHERE `key` = 'yacht'), 'en', 'Yacht');