<?php 


//Setting

__('Site Information');
__('General Configuration');
__('General Configuration');
__('Website Settings');
__('Android & IOS Apps');
__('Site Images');
__('General Settings');
__('Login & Registration');
__('User Configuration');
__('Spam & Banning Tools');
__('FFMPEG Configuration');
__('E-mail Settings');
__('Broadcast');
__('Report');
__('General Settings');
__('Google AdMod');
__('Post');
__('Landing page settings');
__('Sitemap settings');
__('Auto translate settings');
__('Watermark');
__('Progressive Web App');
__('Site title');
__('Give your community a unique name. This will appear in the &lt;title&gt; tag throughout most of your site.');
__('Site description');
__('Enter a brief, concise description of your community. Include any keywords or phrases that you want to appear in search engine listings.');
__('Site keywords');
__('Provide some keywords (separated by commas) that describe your community. These will be the default keywords that appear in the &lt;meta&gt; tag in your page header. Enter the most relevant keywords you can think of to help your community\'s search engine rankings.');
__('Site email');
__('Site logo');
__('We recommend using an image with a resolution of 200x40 for the site logo.');
__('Header logo on mobile');
__('We recommend using an image with a resolution of 200x40 for the header logo on mobile.');
__('Site url');
__('From name');
__('Enter the name you want the emails from the system to come from in the field below.');
__('From address');
__('Enter the email address you want the emails from the system to come from in the field below.');
__('Mail engine');
__('Emails typically get sent through the web server using the PHP mail() function. Alternatively, you can have emails sent out using SMTP, usually requiring a username and password, and optionally using an external mail server.');
__('Mail');
__('SMTP');
__('Hostname');
__('In some cases, you might need to include ssl:// in the hostname.');
__('Port');
__('Default: 25. Also commonly on port 465 (SMTP over SSL) or port 587.');
__('Username');
__('Password');
__('Encryption');
__('None');
__('SSL');
__('TLS');
__('Email queue');
__('Utilizing an email queue, you can allow your website to throttle the emails being sent out to prevent overloading the mail server.');
__('Yes, enable email queue');
__('No, always send emails immediately');
__('Mail count');
__('The number of emails to send out each time the Background Mailer task is run.');
__('Enable email Log');
__('Yes');
__('No');
__('Version');
__('Cache number');
__('Max upload size per file (Mb)');
__('Hashtag trending setting (days)');
__('Trends are determined by an algorithm that is based on the topics that are popular within the “x days” that you configured here rather than topics that have been popular for a while or on a daily basis, to help your members discover the hottest emerging topics of your platform.');
__('Auto approve new hashtag');
__('Home feed only loads activities that have been created since (days)');
__('To optimize the loading speed of the home page, the system will only load the activities that have been created since x days that you configured here.');
__('User notifications settings (days)');
__('To optimize the notifications system, the system will only show the notifications that have been sent to users x days that you configure here.');
__('Friend invitation by email setting (please enter 1-> 100)');
__('Specify the maximum number of emails each time a member can send invitations on the \'invite\' page. If you enter a value that is not valid, the system will use the default value of 10.');
__('Number of invitations that can be sent per day (please enter 1-> 1000)');
__('Specify the maximum number of emails that a user can send in one day. If you enter a value that is not valid, the system will use the default value of 10.');
__('Static File Base URL');
__('The base URL for static files (such as JavaScript and CSS files). Used to implement CDN hosting of static files through services such as Cloudfront.');
__('Notification update frequency (seconds)');
__('The application connects to your server (using AJAX) every few seconds to check if there are any new notifications. How often do you want this process to occur?');
__('Share to friends by email setting (please enter 1-> 100)');
__('Specify the maximum number of emails that a user can type in to share at the \'Share post by email\' page. If you enter a value that is not valid, the system will use the default value of 10.');
__('Share a post - maximum photos can be attached');
__('Maximum photos that member can attach to a post to share (0 or empty setting is unlimited).');
__('Share a post - maximum characters can be posted');
__('Maximum number of characters allowed when creating a post (0 or empty setting is unlimited).');
__('Write a comment/reply - maximum characters can be written.');
__('Maximum number of characters allowed when writing a comment (0 or empty setting is unlimited).');
__('Write a comment/reply -  maximum photos can be attached.');
__('Maximum photos that member can attach to a comment (0 or empty setting is unlimited).');
__('Enable');
__('Id');
__('Key');
__('Secret');
__('Cluster');
__('Host');
__('Port');
__('Scheme');
__('Force TLS');
__('Timezone default');
__('Hashtag suggestion setting (days)');
__('Suggested hashtags are determined by an algorithm and, by default, are tailored for you based on who you follow, what you recently viewed and your interests. This algorithm identifies topics that your members may be interested in that have been shared within the \'x days\' that you configured here rather than topics that have been shared for a while or on a daily basis, to help your members discover the latest topics that they may be interested in inside your platform.');
__('New follower notifications setting (followers)');
__('The system will stop sending \'new follower\' notifications to members whenever his/her follower reaches the value that you configured here to optimize the notification system. Your members also have the option to turn on/off this notification on his/her own profile settings page (0 or empty setting is unlimited).');
__('Maintenance mode');
__('Maintenance mode will prevent site visitors from accessing your website.');
__('Online');
__('Offline (Maintenance Mode)');
__('Maintenance mode message');
__('Maintenance mode Code');
__('Site logo darkmode');
__('We recommend using an image with a resolution of 200x40 for the site logo darkmode.');
__('Header logo on mobile Dark mode');
__('We recommend using an image with a resolution of 200x40 for the header logo on mobile darkmode.');
__('Og image');
__('We recommend using an image with a resolution of 200x200 for og site.');
__('Cover user default image');
__('We recommend using an image with a resolution of 1024x395 for the default user cover image.');
__('Avatar user default image');
__('We recommend using an image with a resolution of 300x300 for the default user avatar image.');
__('Item per page setting');
__('This is a global paging setting that applies to listing pages inside your platform. If you enter 10 here for example, the first page system will only load 10 items and then load more 10...');
__('Enable cookies');
__('You must enter link cookies if you enable this.');
__('Link cookies');
__('Please include protocol http:// or https://');
__('Force Login');
__('Check this to force Guest users to log in to view the site.');
__('API Secret Key');
__('Protecting the REST API service from spam.');
__('Head Scripts/Styles');
__('Anything entered into the box below will be included at the bottom of the &lt;head&gt; tag. If you want to include a script or stylesheet, be sure to use the &lt;script&gt; or &lt;link&gt; tag.');
__('Body Scripts/Styles');
__('Anything entered into the box below will be included at the bottom of the &lt;body&gt; tag. If you want to include a script or stylesheet, be sure to use the &lt;script&gt; or &lt;link&gt; tag.');
__("User's default appearance mode after sign up");
__('If you set dark as default for example, the dark mode will auto set default for all new sign up users.');
__('Light');
__('Dark');
__('System');
__("User's default video auto play mode after sign up");
__('If enabled, videos will autoplay by default. Members can turn it off in Profile -> Settings -> Display');
__('IP address ban');
__('To ban users by their IP address, enter their address into the field below. Addresses should be separated by commas, like 123.45.67.8, 23.45.67.*');
__('Email address ban');
__('To limit signups by email address, enter the addresses into the field below. Addresses should be separated by commas, like email@domain.com, email2@domain.com, *@domain.com. You may use an asterisk (*) as a wildcard character.');
__('Username ban');
__('To limit signups by username, enter the username into the field below. Username should be separated by commas, like SiteAdmin, Postmaster.');
__('Captcha Type');
__('reCAPTCHA');
__('Cloudflare Turnstile');
__('reCAPTCHA Public Key for v3');
__('You can obtain API credentials at: <a href=\"https://www.google.com/recaptcha\">https://www.google.com/recaptcha</a>.');
__('reCAPTCHA Private Key for v3');
__('You can obtain API credentials at: <a href=\"https://www.google.com/recaptcha\">https://www.google.com/recaptcha</a>.');
__('Turnstile site key');
__('You can obtain API credentials at: <a href=\"https://blog.cloudflare.com/turnstile-private-captcha-alternative\">https://blog.cloudflare.com/turnstile-private-captcha-alternative</a>.');
__('Turnstile secret key');
__('You can obtain API credentials at: <a href=\"https://blog.cloudflare.com/turnstile-private-captcha-alternative\">https://blog.cloudflare.com/turnstile-private-captcha-alternative</a>.');
__('Enable captcha in signup form');
__('Enable captcha in login form');
__('Enable captcha in contact form');
__('Enable captcha in share email');
__('Enable captcha in invite email');
__('User registration');
__('Allow users to create accounts on your site.');
__('User activation');
__('Enable this if you want to active users before they can do activities on the site.');
__('Require email validation');
__('Send a validation link after registration.');
__('Invitation only sign up mode');
__('Allows you to switch sites and apps to invitation only sign up mode. If enabled, to sign up a new account, users need to do via a link sent by an existing user inside the system or invitation code.');
__("Allow you to on/off 'Select Tags to Follow' and 'Select Users to Follow' sign up step.");
__('Bad login limit');
__('How many times a user can try to log in before a lockout?');
__('Lockout time (minutes)');
__('For how long should the user stay locked out?');
__('Enable better password policies');
__('If this is enabled, the password must be at least 6 characters in length and must contain at least one upper case letter, one number, and one special character.');
__('Auto-add follows when signing up.');
__('Age restriction');
__('Minimum age. If the \'Date of birth\' field is not required or value of this setting is empty, age restriction will consider as disabled.');
__('Required date of birth');
__('The option will apply for both web and mobile apps. If enabled, this field will show in sign up but will show on in edit profile page as option field. If age restriction is enabled, please enable this option.');
__('Required location');
__('This option will apply for both web and mobile apps. If enabled, this field will show in sign up process and edit profile page as required field. If disabled, the field will not show in sign up but will show on edit profile page as optional field.');
__('Required gender');
__('This option will apply for both web and mobile apps. If enabled, this field will show in sign up process and edit profile page as required field. If disabled, the field will not show in sign up but will show in edit profile page as optional field.');
__('Two-factor authentication (2FA)');
__('Two-factor authentication (2FA) provides an additional layer of security beyond passwords and is strongly recommended. Your member\'s account is protected by requiring both your password and an authentication code from authenticated email.');
__('FFMPEG system');
__('This system will compress, convert, and optimize videos to mp4. This system requires \"ffmpeg\" to be installed on your server.');
__('FFMPEG binary file path');
__('Example: Linux(/usr/bin/ffmpeg) or Windows(C:\\ffmpeg/bin/ffmpeg.exe).');
__('Video duration');
__('Set the max allowed seconds for the video (0 means no limit).');
__('Enable Android app link');
__('Android app link');
__('Your native Android link.');
__('Enable IOS app link');
__('IOS app link');
__('Your native iOS link.');
__('User account deletion');
__('Allow users to delete their account.');
__('Note');
__('How many reports that member gets in 1 day will be auto-banned by system?');
__('Enable Bottom Banner Ads');
__('Enable Full Screen Ads');
__('Full Screen Ads appearance');
__('Full Screen Ads appearance after [x] click.');
__('Logo');
__('Android package name');
__('Apple bundle id');
__('Apple shared secret');
__('Home feed updates');
__('Updates from everyone');
__('Updates from following members and hashtags');
__('Allow to attach files to the post');
__('Supported file formats');
__('Post - maximum files can be attached');
__('Maximum files that member can attach into a post.');
__('Enable Tenor Gifs');
__('Allow gif at comment, reply and post');
__('Default landing page');
__('Custom landing page');
__('Phone verification signup step');
__('Add an extra step to ask member to verify their phone number before using the platform.');
__('Enable reCAPTCHA in send sms');
__('Audio duration');
__('Set the max allowed seconds for the audio (0 means no limit).');
__('Allowed video file extensions');
__('Defines a list of video file extensions that members are allowed to upload. Separate extensions with commas. Empty means that you\'re allowed the following extensions mp4,wmv,3gp,mov,avi.');
__('Enable');
__('Schedule updates');
__('Daily');
__('Weekly');
__('Monthly');
__('Enable');
__('Enable auto translate for post, comment, reply and message');
__('Enable');
__('Auto insert text watermark into the photos in post. If enable, the watermark only apply for the newly added photos');
__('Text');
__('If left blank, the system will automatically use the domain name and username for the text watermark. Ex: domainame.com/@abc');
__('Position');
__('Top Left');
__('Top Center');
__('Top Right');
__('Middle Left');
__('Center');
__('Middle Right');
__('Bottom Left');
__('Bottom Center');
__('Bottom Right');
__('Text color');
__('Text font size (px)');
__('Text style');
__('Regular');
__('Medium');
__('Semibold');
__('Bold');
__('Enable');
__('Firebase json');
__('Firebase key pair');

__('Required photo upload step (Yes/No)');
__('Add an extra step to ask member to verify their photos before using the platform.');
__('Limit upload photos verification');
__('Identity verification signup step');
__('Add an extra step to ask member to verify their identity before using the platform.');

//Permission

__('Manage Site');
__('Post');
__('Site Information');
__('General Configuration');
__('Mail Templates');
__('Manage Menus');
__('Manage Languages');
__('Manage OpenID');
__('Manage Genders');
__('Manage Themes');
__('Layout Editor');
__('Manage Currencies');
__('Mobile General Configuration');
__('Mobile Broadcast Message');
__('Cache Setting');
__('Storage System');
__('Tasks');
__('System Log');
__('Manage Static Pages');
__('Hashtags');
__('Manage Users');
__('Reports');
__('Report Categories');
__('Manage Countries');
__('Manage Subscriptions');
__('Max characters per post');
__('Max video size (duration - seconds) can upload');
__('Allow poll creation');
__('Maximum number of options that can be created for a poll');
__('Maximum number of days allowed to be selected when creating a poll');
__('Content Warning Categories');
__('Manage Sms Providers');
__('Maximum number of post (not include Vibb) can share per day (0 is unlimited)');
__('Maximum number comments (include replies) can share per day (0 is unlimited)');
__('Manage Two-Factor Providers');
__('Manage Link Profile Icons');
__('Manage Translation Providers');
__('Wallets');
__('Deposit packages');
__('Transfer funds requests');
__('Transfer Mass Funds');
__("System's billing activities");
__('Manage Advertisings');
__('Manage AI Feature Tasks');
__('Manage AI Providers');
__('Manage Messages');
__('Manage Payment Gateways');
__('Manage Groups');
__('Group Categories');
__('Paid content subscription packages');
__('Paid content tips packages');
__('Story backgrounds');
__('Story songs');
__('Manage Profiles');
__('Page Categories');
__('Profile Verification Requests');
__('Profile Feature Packages');
__('Manage Packages');
__('Customize Pricing Plans');
__('User verify requests');
__('Vibb songs');

//Email
__('MAIL_HEADER_NAME');
__('MAIL_FOOTER_NAME');
__('MAIL_HEADER_MEMBER_NAME');
__('MAIL_FOOTER_MEMBER_NAME');
__('MAIL_WELCOME_USER_NAME');
__('MAIL_INVITE_EMAIL_NAME');
__('MAIL_DAILY_EMAIL_NAME');
__('MAIL_SHARE_EMAIL_NAME');
__('MAIL_EMAIL_VERIFY_NAME');
__('MAIL_CONTACT_NAME');
__('MAIL_FORGOT_PASSWORD_CODE_NAME');
__('MAIL_ADMIN_CHANGE_PASSWORD_NAME');
__('MAIL_WELCOME_USER_VERIFY_NAME');
__('MAIL_ACTIVE_USER_NAME');
__('MAIL_INACTIVE_USER_NAME');
__('MAIL_WELCOME_USER_WITH_PASSWORD_NAME');
__('MAIL_TWO_FACTORY_SEND_CODE_NAME');
__('MAIL_INACTIVE_USER_REPORT_NAME');

//Task
__('Mail daily run task.');
__('Mail send task.');
__('Post queue run task.');
__('Task Storage Transfer.');
__('Task check status.');
__('Delete user task.');
__('User download run task.');
__('Send notify to user follow task.');

?>
