INSERT INTO `{prefix}settings` (`key`, `name`, `description`, `value`, `params`, `type`, `order`, `group_id`, `group_sub_id`, `hidden`) VALUES
('site.title', 'Site title', 'Give your community a unique name. This will appear in the &lt;title&gt; tag throughout most of your site.', '', '', 'text', 1, 1, 1, 0),
('site.description', 'Site description', 'Enter a brief, concise description of your community. Include any keywords or phrases that you want to appear in search engine listings.', '', '', 'textarea', 2, 1, 1, 0),
('site.keywords', 'Site keywords', "Provide some keywords (separated by commas) that describe your community. These will be the default keywords that appear in the &lt;meta&gt; tag in your page header. Enter the most relevant keywords you can think of to help your community's search engine rankings.", '', '', 'text', 3, 1, 1, 0),
('site.email', 'Site email', '', '', '', 'text', 7, 1, 1, 0),
('site.logo', 'Site logo', 'We recommend using an image with a resolution of 200x40 for the site logo.', '', '{"default":"images/default/logo.png","style_width":"200"}', 'image', 4, 1, 3, 0),
('site.header_mobile_logo_mobile', 'Header logo on mobile', 'We recommend using an image with a resolution of 200x40 for the header logo on mobile.', '', '{"default":"images/default/logo.png","style_width":"200"}', 'image', 4, 1, 3, 0),
('site.url', 'Site url', '', '', '', 'text', 8, 1, 1, 0),
('mail.name', 'From name', 'Enter the name you want the emails from the system to come from in the field below.', '', '', 'text', 1, 2, 9, 0),
('mail.address', 'From address', 'Enter the email address you want the emails from the system to come from in the field below.', '', '', 'text', 2, 2, 9, 0),
('mail.engine', 'Mail engine', 'Emails typically get sent through the web server using the PHP mail() function. Alternatively, you can have emails sent out using SMTP, usually requiring a username and password, and optionally using an external mail server.', 'sendmail', '{"sendmail":"Mail","smtp":"SMTP"}', 'select', 3, 2, 9, 0),
('mail.host', 'Hostname', 'In some cases, you might need to include ssl:// in the hostname.', '', '', 'text', 4, 2, 9, 0),
('mail.port', 'Port', 'Default: 25. Also commonly on port 465 (SMTP over SSL) or port 587.', '25', '', 'text', 5, 2, 9, 0),
('mail.username', 'Username', '', '', '', 'text', 6, 2, 9, 0),
('mail.password', 'Password', '', '', '', 'password', 7, 2, 9, 0),
('mail.encryption', 'Encryption', '', '', '{"":"None","ssl":"SSL", "tls":"TLS"}', 'select', 8, 2, 9, 0),
('mail.queue', 'Email queue', 'Utilizing an email queue, you can allow your website to throttle the emails being sent out to prevent overloading the mail server.', '0', '{"1":"Yes, enable email queue", "0":"No, always send emails immediately"}', 'select', 9, 2, 9, 0),
('mail.count', 'Mail count', 'The number of emails to send out each time the Background Mailer task is run.', '25', '', 'number', 10, 2, 9, 0),
('mail.log', 'Enable email Log', '', '0', '{"1":"Yes", "0":"No"}', 'select', 11, 2, 9, 0),
('site.version', 'Version', '', '1.7', '', 'text', 0, 0, 0, 1),
('site.cache_number', 'Cache number', '', '1', '', 'text', 0, 0, 0, 1),
('feature.file_max_upload', 'Max upload size per file (Mb)', '', '', '', 'number', 7, 2, 4, 0),
-- ('feature.hashtag_trending_delete_day', 'Hashtag trending setting (days)', 'Trends are determined by an algorithm that is based on the topics that are popular within the “x days” that you configured here rather than topics that have been popular for a while or on a daily basis, to help your members discover the hottest emerging topics of your platform.', '60', '', 'number', 8, 2, 4, 0),
-- ('feature.hashtag_auto_approve', 'Auto approve new hashtag', '', '1', '', 'checkbox', 8, 2, 4, 0),
-- ('feature.post_home_delete_day', 'Home feed only loads activities that have been created since (days)', 'To optimize the loading speed of the home page, the system will only load the activities that have been created since x days that you configured here.', '120', '', 'number', 9, 2, 4, 0),
('feature.notify_delete_day', 'User notifications settings (days)', 'To optimize the notifications system, the system will only show the notifications that have been sent to users x days that you configure here.', '120', '', 'number', 10, 2, 4, 0),
('feature.invite_max', 'Friend invitation by email setting (please enter 1-> 100)', "Specify the maximum number of emails each time a member can send invitations on the 'invite' page. If you enter a value that is not valid, the system will use the default value of 10.", '10', '', 'number', 11, 2, 4, 0),
('feature.invite_email_per_day', 'Number of invitations that can be sent per day (please enter 1-> 1000)', 'Specify the maximum number of emails that a user can send in one day. If you enter a value that is not valid, the system will use the default value of 10.', '10', '', 'number', 12, 2, 4, 0),
('site.cdn_url', 'Static File Base URL', 'The base URL for static files (such as JavaScript and CSS files). Used to implement CDN hosting of static files through services such as Cloudfront.', '', '', 'text', 9, 1, 1, 0),
('site.notification_interval', 'Notification update frequency (seconds)', 'The application connects to your server (using AJAX) every few seconds to check if there are any new notifications. How often do you want this process to occur?', '60', '', 'number', 10, 1, 1, 0),
-- ('feature.share_email_max', 'Share to friends by email setting (please enter 1-> 100)', "Specify the maximum number of emails that a user can type in to share at the 'Share post by email' page. If you enter a value that is not valid, the system will use the default value of 10.", '10', '', 'number', 14, 2, 4, 0),
-- ('feature.post_photo_max', 'Share a post - maximum photos can be attached', 'Maximum photos that member can attach to a post to share (0 or empty setting is unlimited).', '10', '', 'number', 15, 2, 14, 0),
-- ('feature.post_character_max', 'Share a post - maximum characters can be posted', 'Maximum number of characters allowed when creating a post (0 or empty setting is unlimited).', '63206', '', 'number', 16, 2, 14, 0),
-- ('feature.comment_character_max', 'Write a comment/reply - maximum characters can be written.', 'Maximum number of characters allowed when writing a comment (0 or empty setting is unlimited).', '8000', '', 'number', 17, 2, 4, 0),
-- ('feature.comment_photo_max', 'Write a comment/reply -  maximum photos can be attached.', 'Maximum photos that member can attach to a comment (0 or empty setting is unlimited).', '10', '', 'number', 18, 2, 4, 0),
('broadcast.enable', 'Enable', '', '0', '', 'checkbox', 1, 2, 10, 0),
('broadcast.id', 'Id', '', '', '', 'text', 2, 2, 10, 0),
('broadcast.key', 'Key', '', '', '', 'text', 3, 2, 10, 0),
('broadcast.secret', 'Secret', '', '', '', 'text', 4, 2, 10, 0),
('broadcast.cluster', 'Cluster', '', '', '', 'text', 5, 2, 10, 0),
('broadcast.host', 'Host', '', '', '', 'text', 6, 2, 10, 0),
('broadcast.port', 'Port', '', '', '', 'text', 7, 2, 10, 0),
('broadcast.scheme', 'Scheme', '', '', '', 'text', 8, 2, 10, 0),
('broadcast.force_tls', 'Force TLS', '', '0', '', 'checkbox', 9, 2, 10, 0),
('site.timezone', 'Timezone default', '', 'Europe/London', '{"path":"shaun_core::admin.partial.setting.name.timezone"}', 'blade', 11, 1, 1, 0),
-- ('feature.user_suggest_hastag_delete_day', 'Hashtag suggestion setting (days)', "Suggested hashtags are determined by an algorithm and, by default, are tailored for you based on who you follow, what you recently viewed and your interests. This algorithm identifies topics that your members may be interested in that have been shared within the 'x days' that you configured here rather than topics that have been shared for a while or on a daily basis, to help your members discover the latest topics that they may be interested in inside your platform.", '60', '', 'number', 18, 2, 4, 0),
-- ('feature.max_follow_get_notification', 'New follower notifications setting (followers)', "The system will stop sending 'new follower' notifications to members whenever his/her follower reaches the value that you configured here to optimize the notification system. Your members also have the option to turn on/off this notification on his/her own profile settings page (0 or empty setting is unlimited).", '1000', '', 'number', 19, 2, 4, 0),
('site.offline', 'Maintenance mode', 'Maintenance mode will prevent site visitors from accessing your website.', '0', '{"0":"Online","1":"Offline (Maintenance Mode)"}', 'radio', 4, 1, 1, 0),
('site.offline_message', 'Maintenance mode message', '', 'We are temporarily offline for upgrading to the latest version, this site will be online soon.', '', 'textarea', 6, 1, 1, 0),
('site.offline_code', 'Maintenance mode Code', '', '123456', '', 'text', 5, 1, 1, 0),
('site.logo_darkmode', 'Site logo darkmode', 'We recommend using an image with a resolution of 200x40 for the site logo darkmode.', '', '{"default":"images/default/logo_darkmode.png","style_width":"200"}', 'image', 22, 1, 3, 0),
('site.header_mobile_logo_mobile_darkmode', 'Header logo on mobile Dark mode', 'We recommend using an image with a resolution of 200x40 for the header logo on mobile darkmode.', '', '{"default":"images/default/logo_darkmode.png","style_width":"200"}', 'image', 22, 1, 3, 0),
('site.og_image', 'Og image', 'We recommend using an image with a resolution of 200x200 for og site.', '', '{"style_width":"200"}', 'image', 23, 1, 3, 0),
('feature.cover_default', 'Cover user default image', 'We recommend using an image with a resolution of 1024x395 for the default user cover image.', '', '{"default":"images/default/cover_user.png","style_width":"200"}', 'image', 25, 1, 3, 0),
('feature.avatar_default', 'Avatar user default image', 'We recommend using an image with a resolution of 300x300 for the default user avatar image.', '', '{"default":"images/default/avatar_user.png","style_width":"50","class":"rounded-full"}', 'image', 26, 1, 3, 0),
('feature.item_per_page', 'Item per page setting', 'This is a global paging setting that applies to listing pages inside your platform. If you enter 10 here for example, the first page system will only load 10 items and then load more 10...', '10', '', 'text', 20, 2, 4, 0),
('feature.cookie_enable', 'Enable cookies', 'You must enter link cookies if you enable this.', '1', '', 'checkbox', 21, 2, 4, 0),
('feature.cookie_link', 'Link cookies', 'Please include protocol http:// or https://', '', '', 'text', 22, 2, 4, 0),
('feature.force_login', 'Force Login', 'Check this to force Guest users to log in to view the site.', '0', '', 'checkbox', 23, 2, 4, 0),
('app.api_secret_key', 'API Secret Key', 'Protecting the REST API service from spam.', '', '', 'text', 24, 2, 4, 0),
('site.head_script', 'Head Scripts/Styles', 'Anything entered into the box below will be included at the bottom of the &lt;head&gt; tag. If you want to include a script or stylesheet, be sure to use the &lt;script&gt; or &lt;link&gt; tag.', '', '', 'textarea', 12, 1, 1, 0),
('site.body_script', 'Body Scripts/Styles', 'Anything entered into the box below will be included at the bottom of the &lt;body&gt; tag. If you want to include a script or stylesheet, be sure to use the &lt;script&gt; or &lt;link&gt; tag.', '', '', 'textarea', 13, 1, 1, 0),
('site.appearance_mode_default', "User's default appearance mode after sign up", 'If you set dark as default for example, the dark mode will auto set default for all new sign up users.', 'off', '{"off":"Light","on":"Dark", "auto": "System"}', 'radio', 13, 2, 5, 0),
('site.autoplay_video_default', "User's default video auto play mode after sign up", 'If enabled, videos will autoplay by default. Members can turn it off in Profile -> Settings -> Display', '1', '', 'checkbox', 14, 2, 5, 0),
('spam.ip_ban', 'IP address ban', 'To ban users by their IP address, enter their address into the field below. Addresses should be separated by commas, like 123.45.67.8, 23.45.67.*', '', '', 'textarea', 1, 2, 7, 0),
('spam.email_ban', 'Email address ban', 'To limit signups by email address, enter the addresses into the field below. Addresses should be separated by commas, like email@domain.com, email2@domain.com, *@domain.com. You may use an asterisk (*) as a wildcard character.', '', '', 'textarea', 2, 2, 7, 0),
('spam.username_ban', 'Username ban', 'To limit signups by username, enter the username into the field below. Username should be separated by commas, like SiteAdmin, Postmaster.', '', '', 'textarea', 3, 2, 7, 0),
('spam.capcha_type', 'Captcha Type', '', 'recaptcha', '{"recaptcha":"reCAPTCHA", "turnstile":"Cloudflare Turnstile"}', 'select', 3, 2, 7, 0),
('spam.recapcha_public_key', 'reCAPTCHA Public Key for v3', 'You can obtain API credentials at: <a href="https://www.google.com/recaptcha">https://www.google.com/recaptcha</a>.', '', '', 'text', 4, 2, 7, 0),
('spam.recapcha_private_key', 'reCAPTCHA Private Key for v3', 'You can obtain API credentials at: <a href="https://www.google.com/recaptcha">https://www.google.com/recaptcha</a>.', '', '', 'text', 5, 2, 7, 0),
('spam.turnstile_site_key', 'Turnstile site key', 'You can obtain API credentials at: <a href="https://blog.cloudflare.com/turnstile-private-captcha-alternative">https://blog.cloudflare.com/turnstile-private-captcha-alternative</a>.', '', '', 'text', 5, 2, 7, 0),
('spam.turnstile_secret_key', 'Turnstile secret key', 'You can obtain API credentials at: <a href="https://blog.cloudflare.com/turnstile-private-captcha-alternative">https://blog.cloudflare.com/turnstile-private-captcha-alternative</a>.', '', '', 'text', 5, 2, 7, 0),
('spam.signup_enable_recapcha', 'Enable captcha in signup form', '', '0', '', 'checkbox', 6, 2, 7, 0),
('spam.login_enable_recapcha', 'Enable captcha in login form', '', '0', '', 'checkbox', 7, 2, 7, 0),
('spam.contact_enable_recapcha', 'Enable captcha in contact form', '', '0', '', 'checkbox', 8, 2, 7, 0),
('spam.share_email_enable_recapcha', 'Enable captcha in share email', '', '0', '', 'checkbox', 9, 2, 7, 0),
('spam.invite_email_enable_recapcha', 'Enable captcha in invite email', '', '0', '', 'checkbox', 10, 2, 7, 0),
('feature.enable_signup', 'User registration', 'Allow users to create accounts on your site.', '1', '', 'checkbox', 1, 2, 5, 0),
('feature.enable_must_active', 'User activation', 'Enable this if you want to active users before they can do activities on the site.', '0', '', 'checkbox', 2, 2, 5, 0),
('feature.email_verify', 'Require email validation', 'Send a validation link after registration.', '0', '', 'checkbox', 3, 2, 5, 0),
('feature.invite_only', 'Invitation only sign up mode', 'Allows you to switch sites and apps to invitation only sign up mode. If enabled, to sign up a new account, users need to do via a link sent by an existing user inside the system or invitation code.', '0', '', 'checkbox', 4, 2, 5, 0),
('feature.bad_login_limit', 'Bad login limit', 'How many times a user can try to log in before a lockout?', '10', '', 'number', 4, 2, 5, 0),
('feature.bad_login_time', 'Lockout time (minutes)', 'For how long should the user stay locked out?', '1', '', 'number', 5, 2, 5, 0),
('feature.better_password', 'Enable better password policies', 'If this is enabled, the password must be at least 6 characters in length and must contain at least one upper case letter, one number, and one special character.', '0', '', 'checkbox', 6, 2, 5, 0),
-- ('feature.auto_follow', 'Auto-add follows when signing up.', '', '', '{"path":"shaun_core::admin.partial.setting.name.auto_follow"}', 'blade', 7, 2, 5, 0),
('feature.age_restriction', 'Age restriction', "Minimum age. If the 'Date of birth' field is not required or value of this setting is empty, age restriction will consider as disabled.", '0', '', 'number', 8, 2, 5, 0),
('feature.require_birth', 'Required date of birth', 'The option will apply for both web and mobile apps. If enabled, this field will show in sign up but will show on in edit profile page as option field. If age restriction is enabled, please enable this option.', '0', '', 'checkbox', 9, 2, 5, 0),
('feature.require_location', 'Required location', 'This option will apply for both web and mobile apps. If enabled, this field will show in sign up process and edit profile page as required field. If disabled, the field will not show in sign up but will show on edit profile page as optional field.', '0', '', 'checkbox', 10, 2, 5, 0),
('feature.require_gender', 'Required gender', 'This option will apply for both web and mobile apps. If enabled, this field will show in sign up process and edit profile page as required field. If disabled, the field will not show in sign up but will show in edit profile page as optional field.', '0', '', 'checkbox', 11, 2, 5, 0),
('feature.enable_two_factor', 'Two-factor authentication (2FA)', "Two-factor authentication (2FA) provides an additional layer of security beyond passwords and is strongly recommended. Your member's account is protected by requiring both your password and an authentication code from authenticated email.", '0', '', 'checkbox', 12, 2, 5, 0),
('feature.ffmpeg_enable', 'FFMPEG system', 'This system will compress, convert, and optimize videos to mp4. This system requires "ffmpeg" to be installed on your server.', '0', '', 'checkbox', 1, 2, 8, 0),
('feature.ffmpeg_path', 'FFMPEG binary file path', 'Example: Linux(/usr/bin/ffmpeg) or Windows(C:\\ffmpeg/bin/ffmpeg.exe).', '', '', 'text', 2, 2, 8, 0),
('feature.video_max_duration', 'Video duration', 'Set the max allowed seconds for the video (0 means no limit).', '60', '', 'number', 3, 2, 8, 0),
-- ('site.enable_android_link', 'Enable Android app link', '', '', '', 'checkbox', 1, 1, 2, 0),
-- ('site.android_link', 'Android app link', 'Your native Android link.', '', '', 'text', 2, 1, 2, 0),
-- ('site.enable_ios_link', 'Enable IOS app link', '', '', '', 'checkbox', 3, 1, 2, 0),
-- ('site.ios_link', 'IOS app link', 'Your native iOS link.', '', '', 'text', 4, 1, 2, 0),
('user.allow_delete', 'User account deletion', 'Allow users to delete their account.', '1', '', 'checkbox', 1, 2, 6, 0),
('site.note', 'Note', '', '', '', 'text', 0, 0, 0, 1),
('report.time_disable_user', 'How many reports that member gets in 1 day will be auto-banned by system?', '', '5', '', 'text', 1, 2, 11, 0),
('mobile.enable_bottom_banner_ads', 'Enable Bottom Banner Ads', '', '', '', 'checkbox', 2, 3, 13, 0),
('mobile.enable_fullscreen_ads', 'Enable Full Screen Ads', '', '', '', 'checkbox', 4, 3, 13, 0),
('mobile.fullscreen_ads_number_click', 'Full Screen Ads appearance', 'Full Screen Ads appearance after [x] click.', '5', '', 'number', 4, 3, 13, 0),
-- ('site.app_suggest_photo', 'Logo', '', '', '{"default":"images/default/app_suggest_default.png","style_width":"100"}', 'image', 5, 1, 2, 0),
('mobile.android_package_name', 'Android package name', '', '', '', 'text', 2, 3, 12, 0),
('mobile.apple_bundle_id', 'Apple bundle id', '', '', '', 'text', 3, 3, 12, 0),
('mobile.apple_shared_secret', 'Apple shared secret', '', '', '', 'text', 3, 3, 12, 0),
-- ('site.home_feed_type', 'Home feed updates', '', '0', '{"0":"Updates from everyone", "1":"Updates from following members and hashtags"}', 'select', 25, 2, 4, 0),
-- ('post.upload_files_enable', 'Allow to attach files to the post', '', '1', '', 'checkbox', 1, 2, 14, 0),
-- ('post.support_files', 'Supported file formats', '', 'txt,doc,docx,csv,xls,xlsx,ppt,pptx,pdf,ai,psd', '', 'text', 2, 2, 14, 0),
-- ('post.post_file_max', 'Post - maximum files can be attached', 'Maximum files that member can attach into a post.', '10', '', 'number', 3, 2, 14, 0),
-- ('post.enable_gifs', 'Enable Tenor Gifs', 'Allow gif at comment, reply and post', '1', '', 'checkbox', 4, 2, 14, 0),
('landing.type', '', '', '2', '{"0":"Default landing page", "1":"Custom landing page", "2":"Landing page dating"}', 'radio', 1, 2, 15, 0),
('feature.phone_verify', 'Phone verification signup step', 'Add an extra step to ask member to verify their phone number before using the platform.', '0', '', 'checkbox', 3, 2, 5, 0),
('spam.send_phone_enable_recapcha', 'Enable reCAPTCHA in send sms', '', '0', '', 'checkbox', 11, 2, 7, 0),
('feature.audio_max_duration', 'Audio duration', 'Set the max allowed seconds for the audio (0 means no limit).', '120', '', 'number', 3, 2, 8, 0),
('feature.video_support_files', 'Allowed video file extensions', "Defines a list of video file extensions that members are allowed to upload. Separate extensions with commas. Empty means that you're allowed the following extensions mp4,wmv,3gp,mov,avi.", 'mp4,wmv,3gp,mov,avi', '', 'text', 4, 2, 8, 0),
('sitemap.enable', 'Enable', '', '1', '', 'checkbox', 1, 2, 16, 0),
('sitemap.schedule', 'Schedule updates', '', 'daily', '{"daily":"Daily", "weekly":"Weekly","monthly": "Monthly"}', 'select', 2, 2, 16, 0),
('content_translate.enable', 'Enable', 'Enable auto translate for post, comment, reply and message', '0', '', 'checkbox', 1, 2, 17, 0),
-- ('watermark.enable', 'Enable', "Auto insert text watermark into the photos in post. If enable, the watermark only apply for the newly added photos", '0', '', 'checkbox', 1, 2, 18, 0),
-- ('watermark.text', 'Text', 'If left blank, the system will automatically use the domain name and username for the text watermark. Ex: domainame.com/@abc', '', '', 'text', 2, 2, 18, 0),
-- ('watermark.position', 'Position', '', 'center', '{"top_left":"Top Left", "top_center": "Top Center", "top_right": "Top Right", "middle_left": "Middle Left", "center":"Center", "middle_right": "Middle Right", "bottom_left": "Bottom Left", "bottom_center": "Bottom Center", "bottom_right": "Bottom Right"}', 'select', 3, 2, 18, 0),
-- ('watermark.text_color', 'Text color', '', '#ffffff', '', 'color', 4, 2, 18, 0),
-- ('watermark.text_size', 'Text font size (px)', '', '24', '', 'text', 5, 2, 18, 0),
-- ('watermark.text_style', 'Text style', '', 'regular', '{"regular": "Regular", "medium": "Medium", "semibold": "Semibold", "bold": "Bold"}', 'select', 6, 2, 18, 0),
('pwa.enable', 'Enable', "", '0', '', 'checkbox', 1, 2, 19, 0),
('pwa.icon', 'Icon', "", '', '{"default":"images/default/pwa/icon.png"}', 'image', 2, 2, 19, 0),
('pwa.json', 'Firebase json', "", '', '', 'textarea', 3, 2, 19, 0),
('pwa.key_pair', 'Firebase key pair', "", '', '', 'text', 4, 2, 19, 0);


INSERT INTO `{prefix}setting_groups` (`id`, `name`, `key`, `order`) VALUES
(1, 'Site Information', 'site', 1),
(2, 'General Configuration', 'general', 2),
(3, 'General Configuration', 'mobile_general', 3);

INSERT INTO `{prefix}setting_group_subs` (`id`, `name`, `group_id`, `key`, `order`)  VALUES 
(1, 'Website Settings', '1', 'setting', '1'),
-- (2, 'Android & IOS Apps', '1', 'app', '3'),
(3, 'Site Images', '1', 'image', '2'),
(4, 'General Settings', '2', 'general', '1'),
(5, 'Login & Registration', '2', 'login', '2'),
(6, 'User Configuration', '2', 'user', '3'),
(7, 'Spam & Banning Tools', '2', 'spam', '4'),
(8, 'FFMPEG Configuration', '2', 'ffmpeg', '5'),
(9, 'E-mail Settings', '2', 'email', '6'),
(10, 'Broadcast', '2', 'broadcast', '7'),
(11, 'Report', '2', 'report', '8'),
(12, 'General Settings', '3', 'mobile_general', '1'),
(13, 'Google AdMod', '3', 'mobile_google_admod', '2'),
-- (14, 'Post', '2', 'post', '2'),
-- (15, 'Landing page settings', '2', 'landing', '4'),
(16, 'Sitemap settings', '2', 'sitemap', '5'),
-- (18, 'Watermark', '2', 'watermark', '7'),
(19, 'Progressive Web App', '2', 'pwa', '9');

INSERT INTO `{prefix}roles` (`id`, `name`, `is_moderator`, `is_supper_admin`, `is_default`, `created_at`, `updated_at`) VALUES
(1, 'Super admin', 0, 1, 0, NOW(), NOW()),
(2, 'Member', 0, 0, 1, NOW(), NOW()),
(3, 'Guest', 0, 0, 0, NOW(), NOW());

INSERT INTO `{prefix}permission_groups` (`id`, `name`, `key`, `created_at`, `updated_at`, `order`) VALUES
(1, 'Manage Site', 'admin', NOW(), NOW(), 1);

INSERT INTO `{prefix}permissions` (`name`, `key`, `is_support_guest`, `group_id`, `created_at`, `updated_at`, `type`, `is_support_moderator`, `order`, `description`) VALUES
('Site Information', 'admin.setting.site', 0, 1, NOW(), NOW(), 'checkbox', 1, 1, ''),
('General Configuration', 'admin.setting.general', 0, 1, NOW(), NOW(), 'checkbox', 1, 2, ''),
('Mail Templates', 'admin.mail.manage', 0, 1, NOW(), NOW(), 'checkbox', 1, 3, ''),
('Manage Menus', 'admin.menu.manage', 0, 1, NOW(), NOW(), 'checkbox', 1, 4, ''),
('Manage Languages', 'admin.language.manage', 0, 1, NOW(), NOW(), 'checkbox', 1, 5, ''),
('Manage OpenID', 'admin.openid.manage', 0, 1, NOW(), NOW(), 'checkbox', 1, 6, ''),
('Manage Genders', 'admin.gender.manage', 0, 1, NOW(), NOW(), 'checkbox', 1, 7, ''),
('Manage Themes', 'admin.theme.manage', 0, 1, NOW(), NOW(), 'checkbox', 1, 8, ''),
('Layout Editor', 'admin.layout.manage', 0, 1, NOW(), NOW(), 'checkbox', 1, 9, ''),
('Manage Currencies', 'admin.currency.manage', 0, 1, NOW(), NOW(), 'checkbox', 1, 10, ''),
('Mobile General Configuration', 'admin.setting.mobile_general', 0, 1, NOW(), NOW(), 'checkbox', 1, 12, ''),
('Mobile Broadcast Message', 'admin.mobile.broadcast_message', 0, 1, NOW(), NOW(), 'checkbox', 1, 13, ''),
('Cache Setting', 'admin.cache.setting', 0, 1, NOW(), NOW(), 'checkbox', 1, 14, ''),
('Storage System', 'admin.storage.manage', 0, 1, NOW(), NOW(), 'checkbox', 1, 15, ''),
('Tasks', 'admin.task.manage', 0, 1, NOW(), NOW(), 'checkbox', 1, 16, ''),
('System Log', 'admin.log.manage', 0, 1, NOW(), NOW(), 'checkbox', 1, 17, ''),
('Manage Static Pages', 'admin.page.manage', 0, 1, NOW(), NOW(), 'checkbox', 1, 18, ''),
('Hashtags', 'admin.hashtag.manage', 0, 1, NOW(), NOW(), 'checkbox', 1, 19, ''),
('Manage Users', 'admin.user.manage', 0, 1, NOW(), NOW(), 'checkbox', 1, 20, ''),
('Reports', 'admin.report.manage', 0, 1, NOW(), NOW(), 'checkbox', 1, 21, ''),
('Report Categories', 'admin.report.manage_category', 0, 1, NOW(), NOW(), 'checkbox', 1, 22, ''),
('Manage Countries', 'admin.country.manage', 0, 1, NOW(), NOW(), 'checkbox', 1, 23, ''),
('Manage Subscriptions', 'admin.subscription.manage', 0, 1, NOW(), NOW(), 'checkbox', 1, 24, ''),
('Content Warning Categories', 'admin.content_warning.manage_category', 0, 1, NOW(), NOW(), 'checkbox', 1, 24, ''),
('Manage Sms Providers', 'admin.sms_provider.manage', 0, 1, NOW(), NOW(), 'checkbox', 1, 25, ''),
('Manage Two-Factor Providers', 'admin.two_factor_provider.manage', 0, 1, NOW(), NOW(), 'checkbox', 1, 26, ''),
('Manage Link Profile Icons', 'admin.link_icon.manage', 0, 1, NOW(), NOW(), 'checkbox', 1, 27, ''),
('Manage Translation Providers', 'admin.translate_provider.manage', 0, 1, NOW(), NOW(), 'checkbox', 1, 28, '');

INSERT INTO `{prefix}languages` (`id`, `key`, `name`, `is_default`, `is_rtl`)
VALUES (1, 'en', 'English', '1', '0');

INSERT INTO `{prefix}menus` (`id`, `name`, `alias`, `support_icon`, `support_child`) VALUES 
(1, 'Main Menu', 'main', 1, 1), 
(2, 'Mobile Application Menu', 'mobile_menu', 1, 1), 
(3, 'Footer Menu', 'footer', 0, 0),
(4, 'Profile menu', 'profile', 1, 1);



INSERT INTO `{prefix}menu_items` (`id`, `name`, `url`, `menu_id`, `parent_id`, `is_active`, `is_new_tab`, `is_header`, `icon_file_id`, `icon_default`, `type`, `role_access`, `is_core`, `alias`, `order`, `created_at`, `updated_at`) VALUES
-- (1, 'Home', '', 1, 0, 0, 0, 0, NULL, 'images/default/menu/home.svg', 'internal', '["all"]', 1, '', 1, NOW(), NOW()),
-- (2, 'Discovery', 'discovery', 1, 0, 0, 0, 0, NULL, 'images/default/menu/discovery.svg', 'internal', '["all"]', 1, 'discovery', 2, NOW(), NOW()),
-- (3, 'Watch', 'watch', 1, 0, 0, 0, 0, NULL, 'images/default/menu/watch.svg', 'internal', '["all"]', 1, 'watch', 3, NOW(), NOW()),
(4, 'Lists', 'lists', 1, 0, 1, 0, 0, NULL, 'images/default/menu/list.svg', 'internal', '["all"]', 1, 'list', 4, NOW(), NOW()),
-- (5, 'Bookmarks', 'bookmarks', 1, 0, 0, 0, 0, NULL, 'images/default/menu/bookmark.svg', 'internal', '["all"]', 1, 'bookmark', 5, NOW(), NOW()),
(6, 'Settings', 'settings', 1, 0, 1, 0, 0, NULL, 'images/default/menu/setting.svg', 'internal', '["all"]', 1, 'setting', 6, NOW(), NOW()),
(7, 'Invite', 'invites', 1, 0, 1, 0, 0, NULL, 'images/default/menu/invite.svg', 'internal', '["all"]', 1, 'invite', 7, NOW(), NOW()),
(8, 'Logout', 'logout', 1, 0, 1, 0, 0, NULL, 'images/default/menu/logout.svg', 'internal', '["all"]', 1, 'logout', 8, NOW(), NOW()),
(9, 'Terms of Service', 'sp/terms-of-service', 3, 0, 1, 0, 0, NULL, NULL, 'internal', '["all"]', 0, NULL, 1,  NOW(), NOW()),
(10, 'Privacy Policy', 'sp/privacy-policy', 3, 0, 1, 0, 0, NULL, NULL, 'internal', '["all"]', 0, NULL, 2,  NOW(), NOW()),
(11, 'About us', 'sp/about-us', 3, 0, 1, 0, 0, NULL, NULL, 'internal', '["all"]', 0, NULL, 3,  NOW(), NOW()),
(12, 'Contact us', 'contact', 3, 0, 1, 0, 0, NULL, NULL, 'internal', '["all"]', 0, NULL, 4,  NOW(), NOW()),
-- (13, 'Watch', 'watch', 2, 0, 0, 0, 0, NULL, 'images/default/menu/watch.svg', 'internal', '["all"]', 1, 'watch', 3, NOW(), NOW()),
(14, 'Lists', 'lists', 2, 0, 1, 0, 0, NULL, 'images/default/menu/list.svg', 'internal', '["all"]', 1, 'list', 4, NOW(), NOW()),
-- (15, 'Bookmarks', 'bookmarks', 2, 0, 0, 0, 0, NULL, 'images/default/menu/bookmark.svg', 'internal', '["all"]', 1, 'bookmark', 5, NOW(), NOW()),
(16, 'Settings', 'settings', 2, 0, 1, 0, 0, NULL, 'images/default/menu/setting.svg', 'internal', '["all"]', 1, 'setting', 6, NOW(), NOW()),
(17, 'Invite', 'invites', 2, 0, 1, 0, 0, NULL, 'images/default/menu/invite.svg', 'internal', '["all"]', 1, 'invite', 7, NOW(), NOW()),
(18, 'About', 'about', 2, 0, 0, 0, 0, NULL, 'images/default/menu/about.svg', 'internal', '["all"]', 1, 'about', 9, NOW(), NOW()),
(19, 'Logout', 'logout', 2, 0, 1, 0, 0, NULL, 'images/default/menu/logout.svg', 'internal', '["all"]', 1, 'logout', 8, NOW(), NOW()),
-- (20, 'Media', 'media', 1, 0, 0, 0, 0, NULL, 'images/default/menu/media.svg', 'internal', '["all"]', 1, 'media', 3, NOW(), NOW()),
-- (21, 'Media', 'media', 2, 0, 0, 0, 0, NULL, 'images/default/menu/media.svg', 'internal', '["all"]', 1, 'media', 3, NOW(), NOW()),
-- (22, 'Documents', 'documents', 1, 0, 0, 0, 0, NULL, 'images/default/menu/documents.svg', 'internal', '["all"]', 1, 'documents', 4, NOW(), NOW()),
-- (23, 'Documents', 'documents', 2, 0, 0, 0, 0, NULL, 'images/default/menu/documents.svg', 'internal', '["all"]', 1, 'documents', 4, NOW(), NOW()),
(24, 'Explore', 'explore', 1, 0, 1, 0, 0, NULL, 'images/default/menu/explore.svg', 'internal', '["all"]', 1, 'explore', 2, NOW(), NOW()),
(25, 'Explore', 'explore', 2, 0, 1, 0, 0, NULL, 'images/default/menu/explore.svg', 'internal', '["all"]', 1, 'explore', 2, NOW(), NOW());

INSERT INTO `{prefix}mail_templates` (`id`, `type`, `subject`, `content`, `vars`, `created_at`, `updated_at`, `name`) VALUES
(1, 'header', '', '', '', NOW(), NOW(), 'Header (Non-members)'),
(2, 'footer', '', '', '', NOW(), NOW(), 'Footer (Non-members)'),
(3, 'header_member', '', '', '', NOW(), NOW(), 'Header (Members)'),
(4, 'footer_member', '', '', '', NOW(), NOW(), 'Footer (Members)'),
(5, 'welcome_user', '', '', '[login_link]', NOW(), NOW(), 'Welcome'),
(6, 'invite_email', '', '', '[message],[ref_link]', NOW(), NOW(), 'Invitation'),
(7, 'daily_email', '', '', '[blade]', NOW(), NOW(), 'Notifications summary'),
(8, 'share_email', '', '', '[message],[link]', NOW(), NOW(), 'Shared'),
(9, 'email_verify', '', '', '[code]', NOW(), NOW(), 'Verify email'),
(10, 'contact', '', '', '[name],[email],[subject],[message]', NOW(), NOW(), 'Contact email'),
(11, 'forgot_password_code', '', '', '[code]', NOW(), NOW(), 'Forgot password'),
(12, 'admin_change_password', '', '', '[password]', NOW(), NOW(), 'Admin changes password'),
(13, 'welcome_user_verify', '', '', '[code]', NOW(), NOW(), 'Welcome with verification code'),
(14, 'active_user', '', '', '[link]', NOW(), NOW(), 'Active user'),
(15, 'inactive_user', '', '', '[link]', NOW(), NOW(), 'Inactive user'),
(16, 'welcome_user_with_password', '', '', '[login_link],[password]', NOW(), NOW(), 'Welcome with password'),
(17, 'two_factory_send_code', '', '', '[code]', NOW(), NOW(), 'Two-factor verify email'),
(18, 'inactive_user_report', '', '', '[link]', NOW(), NOW(), 'Auto Inactive by system email');

INSERT INTO `{prefix}translations` (`table_name`, `column_name`, `foreign_key`, `locale`, `value`) VALUES
('mail_templates', 'subject', 1, 'en', ''),
('mail_templates', 'content', 1, 'en', '<p style="margin-top: 0; margin-bottom: 10px">Dear [recipient_name],</p>'),
('mail_templates', 'subject', 2, 'en', ''),
('mail_templates', 'content', 2, 'en', '<p style="line-height: 19px">Best Regards,<br>Social Network Administration</p>'),
('mail_templates', 'subject', 3, 'en', ''),
('mail_templates', 'content', 3, 'en', '<p style="margin-top: 0; margin-bottom: 10px">Dear [recipient_name],</p>'),
('mail_templates', 'subject', 4, 'en', ''),
('mail_templates', 'content', 4, 'en', '<p style="line-height: 19px">Best Regards,<br>Social Network Administration</p>'),
('mail_templates', 'subject', 5, 'en', 'Welcome to [site_name]'),
('mail_templates', 'content', 5, 'en', '<p>[header]</p>\r\n<p>Thank you for joining our social network. Click the following link and enter your information to log in:</p>\r\n<p><a href=\"[login_link]\">[login_link]</a></p>\r\n<p>[footer]</p>'),
('mail_templates', 'subject', 6, 'en', 'You have been invited to join [site_name]'),
('mail_templates', 'content', 6, 'en', '<p>[header]</p><p>[sender_title] has invited you to join our social network. To join, please click on the following link:</p><p><a href="[ref_link]">[ref_link]</a></p><p>[message]</p><p>[footer]</p>'),
('report_categories', 'name', 1, 'en', 'Other'),
('report_categories', 'name', 2, 'en', 'Report from Ai'),
('mail_templates', 'subject', 7, 'en', '[[site_name]] Your Notifications Summary'),
('mail_templates', 'content', 7, 'en', '<p>[header]</p><p>[blade]</p><p>[footer]</p>'),
('mail_templates', 'subject', 8, 'en', 'You have received a sharing link from [site_name]'),
('mail_templates', 'content', 8, 'en', '<p>[header]</p><p>[sender_title] has sent you the sharing link via email. The link is:</p><p><a href="[link]">[link]</a></p><p>[message]</p><p>[footer]</p>'),
('layout_pages', 'title', 1, 'en', 'Header & Footer'),
('layout_pages', 'title', 2, 'en', 'Default Landing Page'),
('layout_pages', 'title', 14, 'en', 'Custom Landing Page'),
('layout_pages', 'title', 15, 'en', 'Explore Page'),
('layout_pages', 'title', 16, 'en', 'Matched Page'),
('layout_pages', 'title', 3, 'en', 'Home Page'),
('layout_contents', 'title', 1, 'en', 'Landing Page Image Block'),
('layout_contents', 'content', 1, 'en', ''),
('layout_contents', 'title', 2, 'en', 'Login Block'),
('layout_contents', 'content', 2, 'en', ''),
('layout_contents', 'title', 3, 'en', 'Login Block'),
('layout_contents', 'content', 3, 'en', ''),
('layout_contents', 'title', 4, 'en', 'Container'),
('layout_contents', 'content', 4, 'en', ''),
('layout_contents', 'title', 5, 'en', 'Container'),
('layout_contents', 'content', 5, 'en', ''),
('genders', 'name', 1, 'en', 'Male'),
('genders', 'name', 2, 'en', 'Female'),
('mail_templates', 'subject', 9, 'en', '[[site_name]] Email Verification'),
('mail_templates', 'content', 9, 'en', '<p>[header]</p><p>To verify your email address and continue, please enter code:</p><p><strong>[code]</strong></p><p>The verification code will expire in 5 minutes.</p><p>[footer]</p>'),
('menu_items', 'name', 1, 'en', 'Home'),
('menu_items', 'name', 2, 'en', 'Discovery'),
('menu_items', 'name', 3, 'en', 'Watch'),
('menu_items', 'name', 4, 'en', 'Lists'),
('menu_items', 'name', 5, 'en', 'Bookmarks'),
('menu_items', 'name', 6, 'en', 'Settings'),
('menu_items', 'name', 7, 'en', 'Invite'),
('menu_items', 'name', 8, 'en', 'Logout'),
('layout_pages', 'title', 4, 'en', 'Discover Page'),
('layout_contents', 'title', 6, 'en', 'Container'),
('layout_contents', 'content', 6, 'en', ''),
('layout_contents', 'title', 7, 'en', 'Container'),
('layout_contents', 'content', 7, 'en', ''),
('layout_pages', 'title', 5, 'en', 'User Profile Page'),
('layout_contents', 'title', 8, 'en', 'Container'),
('layout_contents', 'content', 8, 'en', ''),
('layout_contents', 'title', 9, 'en', 'Container'),
('layout_contents', 'content', 9, 'en', ''),
('layout_pages', 'title', 6, 'en', 'Post Detail Page'),
('layout_contents', 'title', 10, 'en', 'Container'),
('layout_contents', 'content', 10, 'en', ''),
('layout_contents', 'title', 11, 'en', 'Container'),
('layout_contents', 'content', 11, 'en', ''),
('mail_templates', 'subject', 10, 'en', '[[site_name]] A User has sent you a message using the contact page'),
('mail_templates', 'content', 10, 'en', '<p>[header]</p><p>[name] has sent you a message using the contact page:</p><p>Email: [email]</p><p>Subject: [subject]</p><p>Message:</p><p>[message]</p><p>[footer]</p>'),
('pages', 'content', 1, 'en', '<p>This is the Terms of Service page</p>'),
('layout_pages', 'title', 7, 'en', 'Terms of Service'),
('layout_contents', 'title', 12, 'en', 'Container'),
('layout_contents', 'content', 12, 'en', ''),
('layout_contents', 'title', 13, 'en', 'Container'),
('layout_contents', 'content', 13, 'en', ''),
('pages', 'content', 2, 'en', '<p>This is the Privacy Policy page</p>'),
('layout_pages', 'title', 8, 'en', 'Privacy Policy'),
('layout_contents', 'title', 14, 'en', 'Container'),
('layout_contents', 'content', 14, 'en', ''),
('layout_contents', 'title', 15, 'en', 'Container'),
('layout_contents', 'content', 15, 'en', ''),
('pages', 'content', 3, 'en', '<p>This is the About Us page</p>'),
('layout_pages', 'title', 9, 'en', 'About us'),
('layout_contents', 'title', 16, 'en', 'Container'),
('layout_contents', 'content', 16, 'en', ''),
('layout_contents', 'title', 17, 'en', 'Container'),
('layout_contents', 'content', 17, 'en', ''),
('menu_items', 'name', 9, 'en', 'Terms of Service'),
('menu_items', 'name', 10, 'en', 'Privacy Policy'),
('menu_items', 'name', 11, 'en', 'About us'),
('menu_items', 'name', 12, 'en', 'Contact us'),
('mail_templates', 'subject', 11, 'en', '[[site_name]] Account password reset'),
('mail_templates', 'content', 11, 'en', '<p>[header]</p><p>Please use this code to reset the password for your account</p><p>Here is your code: <strong>[code]</strong></p><p>The verification code will expire in 5 minutes.</p><p>[footer]</p>'),
('layout_contents', 'title', 18, 'en', 'Suggested Users'),
('layout_contents', 'content', 18, 'en', ''),
('layout_contents', 'title', 19, 'en', 'Suggested Hashtags'),
('layout_contents', 'content', 19, 'en', ''),
('layout_contents', 'title', 20, 'en', 'Trending Users'),
('layout_contents', 'content', 20, 'en', ''),
('layout_contents', 'title', 21, 'en', 'Trending Hashtags'),
('layout_contents', 'content', 21, 'en', ''),
('mail_templates', 'subject', 12, 'en', '[[site_name]] Your password has been changed'),
('mail_templates', 'content', 12, 'en', '<p>[header]</p><p>The admin has changed your password to <strong>[password]</strong></p><p>[footer]</p>'),
('mail_templates', 'subject', 13, 'en', 'Welcome to [site_name]'),
('mail_templates', 'content', 13, 'en', '<p>[header]</p><p>Thank you for joining our social network. To verify your email address and continue, please enter code:</p><p><strong>[code]</strong></p><p>The verification code will expire in 5 minutes.</p><p>[footer]</p>'),
('layout_contents', 'title', 22, 'en', 'Suggested Users'),
('layout_contents', 'content', 22, 'en', ''),
('mail_templates', 'subject', 14, 'en', '[[site_name]] Your account has been enabled'),
('mail_templates', 'content', 14, 'en', '<p>[header]</p><p>Your account has been enabled by site admin. Enjoy our social network!</p><p><a href="[link]">[link]</a></p><p>[footer]</p>'),
('mail_templates', 'subject', 15, 'en', '[[site_name]] Your account has been disabled'),
('mail_templates', 'content', 15, 'en', '<p>[header]</p><p>Your account has been disabled by site admin. Contact site admin at the below link for more details.</p><p><a href="[link]">[link]</a></p><p>[footer]</p>'),
('layout_pages', 'title', 10, 'en', 'Watch Page'),
('layout_contents', 'title', 23, 'en', 'Container'),
('layout_contents', 'content', 23, 'en', ''),
('layout_contents', 'title', 24, 'en', 'Container'),
('layout_contents', 'content', 24, 'en', ''),
('layout_contents', 'title', 25, 'en', 'Trending Users'),
('layout_contents', 'content', 25, 'en', ''),
('layout_contents', 'title', 26, 'en', 'Trending Hashtags'),
('layout_contents', 'content', 26, 'en', ''),
('menu_items', 'name', 13, 'en', 'Watch'),
('menu_items', 'name', 14, 'en', 'Lists'),
('menu_items', 'name', 15, 'en', 'Bookmarks'),
('menu_items', 'name', 16, 'en', 'Settings'),
('menu_items', 'name', 17, 'en', 'Invite'),
('menu_items', 'name', 18, 'en', 'About'),
('menu_items', 'name', 19, 'en', 'Logout'),
('mail_templates', 'subject', 16, 'en', 'Welcome to [site_name]'),
('mail_templates', 'content', 16, 'en', '<p>[header]</p>\r\n<p>Thank you for joining our social network. Click the following link and enter your information to login:</p>\r\n<p><a href=\"[login_link]\">[login_link]</a></p><p>Password: <b>[password]</b></p>\r\n<p>[footer]</p>'),
('menu_items', 'name', 20, 'en', 'Media'),
('menu_items', 'name', 21, 'en', 'Media'),
('menu_items', 'name', 22, 'en', 'Documents'),
('menu_items', 'name', 23, 'en', 'Documents'),
('menu_items', 'name', 24, 'en', 'Explore'),
('menu_items', 'name', 25, 'en', 'Explore'),
('layout_pages', 'title', 11, 'en', 'Bookmark Page'),
('layout_contents', 'title', 27, 'en', 'Container'),
('layout_contents', 'content', 27, 'en', ''),
('layout_contents', 'title', 28, 'en', 'Container'),
('layout_contents', 'content', 28, 'en', ''),
('layout_contents', 'title', 29, 'en', 'Trending Users'),
('layout_contents', 'content', 29, 'en', ''),
('layout_pages', 'title', 12, 'en', 'Media Page'),
('layout_pages', 'title', 13, 'en', 'Documents Page'),
('layout_contents', 'title', 30, 'en', 'Container'),
('layout_contents', 'content', 30, 'en', ''),
('layout_contents', 'title', 31, 'en', 'Container'),
('layout_contents', 'content', 31, 'en', ''),
('layout_contents', 'title', 32, 'en', 'Trending Users'),
('layout_contents', 'content', 32, 'en', ''),
('layout_contents', 'title', 33, 'en', 'Container'),
('layout_contents', 'content', 33, 'en', ''),
('layout_contents', 'title', 34, 'en', 'Container'),
('layout_contents', 'content', 34, 'en', ''),
('layout_contents', 'title', 37, 'en', 'Container'),
('layout_contents', 'content', 37, 'en', ''),
('layout_contents', 'title', 38, 'en', 'Container'),
('layout_contents', 'content', 38, 'en', ''),
('layout_contents', 'title', 39, 'en', 'Container'),
('layout_contents', 'content', 39, 'en', ''),
('layout_contents', 'title', 40, 'en', 'Container'),
('layout_contents', 'content', 40, 'en', ''),
('layout_contents', 'title', 45, 'en', 'Container'),
('layout_contents', 'content', 45, 'en', ''),
('layout_contents', 'title', 46, 'en', 'Container'),
('layout_contents', 'content', 46, 'en', ''),
('countries','name',1,'en','United States'),
('countries','name',2,'en','United Arab Emirates'),
('countries','name',3,'en','Afghanistan'),
('countries','name',4,'en','Antigua and Barbuda'),
('countries','name',5,'en','Anguilla'),
('countries','name',6,'en','Albania'),
('countries','name',7,'en','Armenia'),
('countries','name',8,'en','Netherlands Antilles'),
('countries','name',9,'en','Angola'),
('countries','name',10,'en','Antarctica'),
('countries','name',11,'en','Argentina'),
('countries','name',12,'en','American Samoa'),
('countries','name',13,'en','Austria'),
('countries','name',14,'en','Australia'),
('countries','name',15,'en','Aruba'),
('countries','name',16,'en','Aland Islands'),
('countries','name',17,'en','Azerbaijan'),
('countries','name',18,'en','Bosnia and Herzegovina'),
('countries','name',19,'en','Barbados'),
('countries','name',20,'en','Bangladesh'),
('countries','name',21,'en','Belgium'),
('countries','name',22,'en','Burkina Faso'),
('countries','name',23,'en','Bulgaria'),
('countries','name',24,'en','Bahrain'),
('countries','name',25,'en','Burundi'),
('countries','name',26,'en','Benin'),
('countries','name',27,'en','Saint Barthelemy'),
('countries','name',28,'en','Bermuda'),
('countries','name',29,'en','Brunei Darussalam'),
('countries','name',30,'en','Bolivia'),
('countries','name',31,'en','Brazil'),
('countries','name',32,'en','Bahamas'),
('countries','name',33,'en','Bhutan'),
('countries','name',34,'en','Bouvet Island'),
('countries','name',35,'en','Botswana'),
('countries','name',36,'en','Belarus'),
('countries','name',37,'en','Belize'),
('countries','name',38,'en','Canada'),
('countries','name',39,'en','Cocos (Keeling) Islands'),
('countries','name',40,'en','Congo, the Democratic Republic of the'),
('countries','name',41,'en','Central African Republic'),
('countries','name',42,'en','Congo'),
('countries','name',43,'en','Switzerland'),
('countries','name',44,'en','Cote D\'Ivoire'),
('countries','name',45,'en','Cook Islands'),
('countries','name',46,'en','Chile'),
('countries','name',47,'en','Cameroon'),
('countries','name',48,'en','China'),
('countries','name',49,'en','Colombia'),
('countries','name',50,'en','Costa Rica'),
('countries','name',51,'en','Cuba'),
('countries','name',52,'en','Cape Verde'),
('countries','name',53,'en','Christmas Island'),
('countries','name',54,'en','Cyprus'),
('countries','name',55,'en','Czech Republic'),
('countries','name',56,'en','Germany'),
('countries','name',57,'en','Djibouti'),
('countries','name',58,'en','Denmark'),
('countries','name',59,'en','Dominica'),
('countries','name',60,'en','Dominican Republic'),
('countries','name',61,'en','Algeria'),
('countries','name',62,'en','Ecuador'),
('countries','name',63,'en','Estonia'),
('countries','name',64,'en','Egypt'),
('countries','name',65,'en','Western Sahara'),
('countries','name',66,'en','Eritrea'),
('countries','name',67,'en','Spain'),
('countries','name',68,'en','Ethiopia'),
('countries','name',69,'en','Finland'),
('countries','name',70,'en','Fiji'),
('countries','name',71,'en','Falkland Islands (Malvinas)'),
('countries','name',72,'en','Micronesia, Federated States of'),
('countries','name',73,'en','Faroe Islands'),
('countries','name',74,'en','France'),
('countries','name',75,'en','Gabon'),
('countries','name',76,'en','United Kingdom'),
('countries','name',77,'en','Grenada'),
('countries','name',78,'en','Georgia'),
('countries','name',79,'en','French Guiana'),
('countries','name',80,'en','Guernsey'),
('countries','name',81,'en','Ghana'),
('countries','name',82,'en','Gibraltar'),
('countries','name',83,'en','Greenland'),
('countries','name',84,'en','Gambia'),
('countries','name',85,'en','Guinea'),
('countries','name',86,'en','Guadeloupe'),
('countries','name',87,'en','Equatorial Guinea'),
('countries','name',88,'en','Greece'),
('countries','name',89,'en','South Georgia and the South Sandwich Islands'),
('countries','name',90,'en','Guatemala'),
('countries','name',91,'en','Guam'),
('countries','name',92,'en','Guinea-Bissau'),
('countries','name',93,'en','Guyana'),
('countries','name',94,'en','Hong Kong'),
('countries','name',95,'en','Heard Island and Mcdonald Islands'),
('countries','name',96,'en','Honduras'),
('countries','name',97,'en','Croatia'),
('countries','name',98,'en','Haiti'),
('countries','name',99,'en','Hungary'),
('countries','name',100,'en','Indonesia'),
('countries','name',101,'en','Ireland'),
('countries','name',102,'en','Israel'),
('countries','name',103,'en','Isle of Man'),
('countries','name',104,'en','India'),
('countries','name',105,'en','British Indian Ocean Territory'),
('countries','name',106,'en','Iraq'),
('countries','name',107,'en','Iran, Islamic Republic of'),
('countries','name',108,'en','Iceland'),
('countries','name',109,'en','Italy'),
('countries','name',110,'en','Jamaica'),
('countries','name',111,'en','Jordan'),
('countries','name',112,'en','Japan'),
('countries','name',113,'en','Kenya'),
('countries','name',114,'en','Kyrgyzstan'),
('countries','name',115,'en','Cambodia'),
('countries','name',116,'en','Kiribati'),
('countries','name',117,'en','Comoros'),
('countries','name',118,'en','Saint Kitts and Nevis'),
('countries','name',119,'en','Korea, Democratic People\'s Republic of'),
('countries','name',120,'en','Korea, Republic of'),
('countries','name',121,'en','Kuwait'),
('countries','name',122,'en','Cayman Islands'),
('countries','name',123,'en','Kazakhstan'),
('countries','name',124,'en','Lao People\'s Democratic Republic'),
('countries','name',125,'en','Lebanon'),
('countries','name',126,'en','Saint Lucia'),
('countries','name',127,'en','Liechtenstein'),
('countries','name',128,'en','Sri Lanka'),
('countries','name',129,'en','Liberia'),
('countries','name',130,'en','Lesotho'),
('countries','name',131,'en','Lithuania'),
('countries','name',132,'en','Luxembourg'),
('countries','name',133,'en','Latvia'),
('countries','name',134,'en','Libyan Arab Jamahiriya'),
('countries','name',135,'en','Morocco'),
('countries','name',136,'en','Monaco'),
('countries','name',137,'en','Moldova, Republic of'),
('countries','name',138,'en','Montenegro'),
('countries','name',139,'en','Madagascar'),
('countries','name',140,'en','Marshall Islands'),
('countries','name',141,'en','Macedonia, the Former Yugoslav Republic of'),
('countries','name',142,'en','Mali'),
('countries','name',143,'en','Myanmar'),
('countries','name',144,'en','Mongolia'),
('countries','name',145,'en','Macao'),
('countries','name',146,'en','Northern Mariana Islands'),
('countries','name',147,'en','Martinique'),
('countries','name',148,'en','Mauritania'),
('countries','name',149,'en','Montserrat'),
('countries','name',150,'en','Malta'),
('countries','name',151,'en','Mauritius'),
('countries','name',152,'en','Maldives'),
('countries','name',153,'en','Malawi'),
('countries','name',154,'en','Mexico'),
('countries','name',155,'en','Malaysia'),
('countries','name',156,'en','Mozambique'),
('countries','name',157,'en','Namibia'),
('countries','name',158,'en','New Caledonia'),
('countries','name',159,'en','Niger'),
('countries','name',160,'en','Norfolk Island'),
('countries','name',161,'en','Nigeria'),
('countries','name',162,'en','Nicaragua'),
('countries','name',163,'en','Netherlands'),
('countries','name',164,'en','Norway'),
('countries','name',165,'en','Nepal'),
('countries','name',166,'en','Nauru'),
('countries','name',167,'en','Niue'),
('countries','name',168,'en','New Zealand'),
('countries','name',169,'en','Oman'),
('countries','name',170,'en','Panama'),
('countries','name',171,'en','Peru'),
('countries','name',172,'en','French Polynesia'),
('countries','name',173,'en','Papua New Guinea'),
('countries','name',174,'en','Philippines'),
('countries','name',175,'en','Pakistan'),
('countries','name',176,'en','Poland'),
('countries','name',177,'en','Saint Pierre and Miquelon'),
('countries','name',178,'en','Pitcairn'),
('countries','name',179,'en','Puerto Rico'),
('countries','name',180,'en','Palestinian Territory, Occupied'),
('countries','name',181,'en','Portugal'),
('countries','name',182,'en','Palau'),
('countries','name',183,'en','Paraguay'),
('countries','name',184,'en','Qatar'),
('countries','name',185,'en','Reunion'),
('countries','name',186,'en','Romania'),
('countries','name',187,'en','Serbia'),
('countries','name',188,'en','Russian Federation'),
('countries','name',189,'en','Rwanda'),
('countries','name',190,'en','Saudi Arabia'),
('countries','name',191,'en','Solomon Islands'),
('countries','name',192,'en','Seychelles'),
('countries','name',193,'en','Sudan'),
('countries','name',194,'en','Sweden'),
('countries','name',195,'en','Singapore'),
('countries','name',196,'en','Saint Helena'),
('countries','name',197,'en','Slovenia'),
('countries','name',198,'en','Svalbard and Jan Mayen'),
('countries','name',199,'en','Slovakia'),
('countries','name',200,'en','Sierra Leone'),
('countries','name',201,'en','San Marino'),
('countries','name',202,'en','Senegal'),
('countries','name',203,'en','Somalia'),
('countries','name',204,'en','Suriname'),
('countries','name',205,'en','Sao Tome and Principe'),
('countries','name',206,'en','El Salvador'),
('countries','name',207,'en','Syrian Arab Republic'),
('countries','name',208,'en','Swaziland'),
('countries','name',209,'en','Turks and Caicos Islands'),
('countries','name',210,'en','Chad'),
('countries','name',211,'en','French Southern Territories'),
('countries','name',212,'en','Togo'),
('countries','name',213,'en','Thailand'),
('countries','name',214,'en','Tajikistan'),
('countries','name',215,'en','Tokelau'),
('countries','name',216,'en','Timor-Leste'),
('countries','name',217,'en','Turkmenistan'),
('countries','name',218,'en','Tunisia'),
('countries','name',219,'en','Tonga'),
('countries','name',220,'en','Turkey'),
('countries','name',221,'en','Trinidad and Tobago'),
('countries','name',222,'en','Tuvalu'),
('countries','name',223,'en','Taiwan, Province of China'),
('countries','name',224,'en','Tanzania, United Republic of'),
('countries','name',225,'en','Ukraine'),
('countries','name',226,'en','Uganda'),
('countries','name',227,'en','United States Minor Outlying Islands'),
('countries','name',228,'en','Andorra'),
('countries','name',229,'en','Uruguay'),
('countries','name',230,'en','Uzbekistan'),
('countries','name',231,'en','Holy See (Vatican City State)'),
('countries','name',232,'en','Saint Vincent and the Grenadines'),
('countries','name',233,'en','Venezuela'),
('countries','name',234,'en','Virgin Islands, British'),
('countries','name',235,'en','Virgin Islands, U.s.'),
('countries','name',236,'en','Viet Nam'),
('countries','name',237,'en','Vanuatu'),
('countries','name',238,'en','Wallis and Futuna'),
('countries','name',239,'en','Samoa'),
('countries','name',240,'en','Yemen'),
('countries','name',241,'en','Mayotte'),
('countries','name',242,'en','South Africa'),
('countries','name',243,'en','Zambia'),
('countries','name',244,'en','Zimbabwe'),
('permissions', 'message_error', 24 ,'en', 'You only can share a post that has max [x] character(s).'),
('permissions', 'message_error', 25 ,'en', 'You only can share a video of a max [x] second(s) long.'),
('states','name',1,'en','Alaska'),
('states','name',2,'en','Alabama'),
('states','name',3,'en','Arkansas'),
('states','name',4,'en','Arizona'),
('states','name',5,'en','California'),
('states','name',6,'en','Colorado'),
('states','name',7,'en','Connecticut'),
('states','name',8,'en','District of Columbia'),
('states','name',9,'en','Delaware'),
('states','name',10,'en','Florida'),
('states','name',11,'en','Georgia'),
('states','name',12,'en','Hawaii'),
('states','name',13,'en','Iowa'),
('states','name',14,'en','Idaho'),
('states','name',15,'en','Illinois'),
('states','name',16,'en','Indiana'),
('states','name',17,'en','Kansas'),
('states','name',18,'en','Kentucky'),
('states','name',19,'en','Louisiana'),
('states','name',20,'en','Massachusetts'),
('states','name',21,'en','Maryland'),
('states','name',22,'en','Maine'),
('states','name',23,'en','Michigan'),
('states','name',24,'en','Minnesota'),
('states','name',25,'en','Missouri'),
('states','name',26,'en','Mississippi'),
('states','name',27,'en','Montana'),
('states','name',28,'en','North Carolina'),
('states','name',29,'en','North Dakota'),
('states','name',30,'en','Nebraska'),
('states','name',31,'en','New Hampshire'),
('states','name',32,'en','New Jersey'),
('states','name',33,'en','New Mexico'),
('states','name',34,'en','Nevada'),
('states','name',35,'en','New York'),
('states','name',36,'en','Ohio'),
('states','name',37,'en','Oklahoma'),
('states','name',38,'en','Oregon'),
('states','name',39,'en','Pennsylvania'),
('states','name',40,'en','Rhode Island'),
('states','name',41,'en','South Carolina'),
('states','name',42,'en','South Dakota'),
('states','name',43,'en','Tennessee'),
('states','name',44,'en','Texas'),
('states','name',45,'en','Utah'),
('states','name',46,'en','Virginia'),
('states','name',47,'en','Vermont'),
('states','name',48,'en','Washington'),
('states','name',49,'en','Wisconsin'),
('states','name',50,'en','West Virginia'),
('states','name',51,'en','Wyoming'),
('permissions', 'message_error',26 ,'en', "You don't have poll creation permission."),
('permissions', 'message_error', 27 ,'en', 'You only can share a poll that has max [x] option(s).'),
('permissions', 'message_error', 28 ,'en', 'You only can share a poll that has max [x] day(s) length'),
('content_warning_categories', 'name', 1, 'en', 'Sensitive'),
('content_warning_categories', 'name', 2, 'en', 'Violence'),
('content_warning_categories', 'name', 3, 'en', 'Nudity'),
('content_warning_categories', 'name', 4, 'en', 'Other'),
('two_factor_providers','name',1,'en','Authentication App'),
('two_factor_providers','description',1,'en','Get codes from an app like Authy, 1Password, Microsoft, Authenticator, or Google Authenticator.'),
('two_factor_providers','name',2,'en','Sms'),
('two_factor_providers','description',2,'en','Receive a unique code via sms.'),
('two_factor_providers','name',3,'en','Mail'),
('two_factor_providers','description',3,'en','Receive a unique code via mail.'),
('mail_templates', 'subject', 17, 'en', '[[site_name]] Email Verification'),
('mail_templates', 'content', 17, 'en', '<p>[header]</p><p>To verify your email address and continue, please enter code:</p><p><strong>[code]</strong></p><p>The verification code will expire in 5 minutes.</p><p>[footer]</p>'),
('layout_contents', 'title', 41, 'en', 'Container'),
('layout_contents', 'content', 41, 'en', ''),
('layout_contents', 'title', 42, 'en', 'Container'),
('layout_contents', 'content', 42, 'en', ''),
('layout_contents', 'title', 43, 'en', 'Trending Users'),
('layout_contents', 'content', 43, 'en', ''),
('layout_contents', 'title', 44, 'en', 'Trending Hashtags'),
('layout_contents', 'content', 44, 'en', ''),
('mail_templates', 'subject', 18, 'en', '[[site_name]] Your account is disabled because it has been reported too many times by members.'),
('mail_templates', 'content', 18, 'en', '<p>[header]</p><p>Your account is disabled because it has been reported to many times by members. Contact site admin at the below link for more details.</p><p><a href="[link]">[link]</a></p><p>[footer]</p>');

INSERT INTO `{prefix}storage_services` (`id`, `name`, `key`, `config`, `is_default`, `extra`) VALUES
(1, 'Local Storage', 'public', '{"url":""}', 1, ''),
(2, 'Amazon S3', 's3', '{"key":"","secret":"","region":"","bucket":"","url":""}', 0, '{"regions":{"us-east-2":"US East (Ohio)","us-east-1":"US East (N. Virginia)","us-west-1":"US West (N. California)","us-west-2":"US West (Oregon)","af-south-1":"Africa (Cape Town)","ap-east-1":"Asia Pacific (Hong Kong)***","ap-southeast-3":"Asia Pacific (Jakarta)","ap-south-1":"Asia Pacific (Mumbai)","ap-northeast-3":"Asia Pacific (Osaka)","ap-northeast-2":"Asia Pacific (Seoul)","ap-southeast-1":"Asia Pacific (Singapore)","ap-southeast-2":"Asia Pacific (Sydney)","ap-northeast-1":"Asia Pacific (Tokyo)","ca-central-1":"Canada (Central)","cn-north-1":"China (Beijing)","cn-northwest-1":"China (Ningxia)","eu-central-1":"Europe (Frankfurt)","eu-west-1":"Europe (Ireland)","eu-west-2":"Europe (London)","eu-south-1":"Europe (Milan)","eu-west-3":"Europe (Paris)","eu-north-1":"Europe (Stockholm)","sa-east-1":"South America (São Paulo)","me-south-1":"Middle East (Bahrain)","us-gov-east-1":"AWS GovCloud (US-East)","us-gov-west-1":"AWS GovCloud (US-West)"}}'),
(3, 'Wasabi S3', 'wasabi', '{"key":"","secret":"","region":"","bucket":"","url":""}', 0, ''),
(4, 'Digitalocean', 'do', '{"key":"","secret":"","bucket":"","endpoint":"","url":""}', 0, ''),
(5, 'Cloudflare R2', 'r2', '{"key":"","secret":"","bucket":"","endpoint":"","url":""}', 0, ''),
(6, 'Backblaze', 'backblaze', '{"key":"","secret":"","bucket":"","endpoint":"","url":""}', 0, '');

INSERT INTO `{prefix}model_maps` (`id`, `subject_type`, `model_class`) VALUES
(1, 'posts', 'Packages\\ShaunSocial\\Core\\Models\\Post'),
(2, 'storage_files', 'Packages\\ShaunSocial\\Core\\Models\\StorageFile'),
(3, 'users', 'Packages\\ShaunSocial\\Core\\Models\\User'),
(4, 'comments', 'Packages\\ShaunSocial\\Core\\Models\\Comment'),
(5, 'comment_replies', 'Packages\\ShaunSocial\\Core\\Models\\CommentReply'),
(6, 'links', 'Packages\\ShaunSocial\\Core\\Models\\Link'),
(7, 'videos', 'Packages\\ShaunSocial\\Core\\Models\\Video'),
(8, 'layout_contents', 'Packages\\ShaunSocial\\Core\\Models\\LayoutContent'),
(9, 'menu_items', 'Packages\\ShaunSocial\\Core\\Models\\MenuItem'),
(10, 'permissions', 'Packages\\ShaunSocial\\Core\\Models\\Permission'),
(11, 'polls', 'Packages\\ShaunSocial\\Core\\Models\\Poll'),
(12, 'content_warning_categories', 'Packages\\ShaunSocial\\Core\\Models\\ContentWarningCategory'),
(13, 'subscriptions', 'Packages\\ShaunSocial\\Core\\Models\\Subscription'),
(14, 'audios', 'Packages\\ShaunSocial\\Core\\Models\\Audio'),
(15, 'two_factor_providers', 'Packages\\ShaunSocial\\Core\\Models\\TwoFactorProvider');

INSERT INTO `{prefix}layout_maps` (`router`, `layout_class`) VALUES
('home', 'Packages\\ShaunSocial\\Core\\Repositories\\Helpers\\Layout\\HomeLayout'),
('sp_detail', 'Packages\\ShaunSocial\\Core\\Repositories\\Helpers\\Layout\\PageLayout'),
('discovery', 'Packages\\ShaunSocial\\Core\\Repositories\\Helpers\\Layout\\DiscoveryLayout'),
('profile', 'Packages\\ShaunSocial\\Core\\Repositories\\Helpers\\Layout\\UserProfileLayout'),
('post', 'Packages\\ShaunSocial\\Core\\Repositories\\Helpers\\Layout\\PostDetailLayout'),
('watch', 'Packages\\ShaunSocial\\Core\\Repositories\\Helpers\\Layout\\WatchLayout'),
('media', 'Packages\\ShaunSocial\\Core\\Repositories\\Helpers\\Layout\\MediaLayout'),
('bookmarks', 'Packages\\ShaunSocial\\Core\\Repositories\\Helpers\\Layout\\BookmarkLayout'),
('documents', 'Packages\\ShaunSocial\\Core\\Repositories\\Helpers\\Layout\\DocumentsLayout'),
('explore', 'Packages\\ShaunSocial\\Core\\Repositories\\Helpers\\Layout\\ExploreLayout');

INSERT INTO `{prefix}report_categories` (`id`, `name`, `is_active`, `order`, `created_at`, `updated_at`, `is_ai`) VALUES
(1, 'Other', '1', '1', NOW(), NOW(), '0'),
(2, 'Report from AI', '1', '1', NOW(), NOW(), '1');

INSERT INTO `{prefix}layout_blocks` (`component`, `title`, `enable`, `class`, `support_header_footer`, `created_at`, `updated_at`) VALUES
('HtmlBlock', 'Html Block', 1, '', 1, NOW(), NOW()),
('LandingPageImage', 'Landing Page Image Block', 1, 'Packages\\ShaunSocial\\Core\\Repositories\\Helpers\\Widget\\LandingPageImageWidget', 0, NOW(), NOW()),
('Login', 'Login Block', 1, '', 0, NOW(), NOW()),
('Signup', 'Signup Block', 1, '', 0, NOW(), NOW());

INSERT INTO `{prefix}layout_pages` (`id`, `type`, `title`, `meta_keywords`, `meta_description`, `router`, `page_id`, `is_delete`, `created_at`, `updated_at`) VALUES
(1, 'header_footer', 'Header && Footer', NULL, NULL, NULL, 0, 0, NOW(), NOW()),
(2, 'router', 'Default Landing Page', NULL, NULL, 'landing_page.index', 0, 1, NOW(), NOW()),
(3, 'router', 'Home Page', NULL, NULL, 'home_page.index', 0, 1, NOW(), NOW()),
(4, 'router', 'Discovery Page', NULL, NULL, 'discovery.index', 0, 1, NOW(), NOW()),
(5, 'router', 'User Profile Page', NULL, NULL, 'user.profile', 0, 1, NOW(), NOW()),
(6, 'router', 'Post Detail Page', NULL, NULL, 'post.detail', 0, 0, NOW(), NOW()),
(7, 'page', 'Terms of Service', NULL, NULL, NULL, 1, 0, NOW(), NOW()),
(8, 'page', 'Privacy Policy', NULL, NULL, NULL, 2, 0, NOW(), NOW()),
(9, 'page', 'About us', NULL, NULL, NULL, 3, 0, NOW(), NOW()),
(10, 'router', 'Watch Page', NULL, NULL, 'watch.index', 0, 1, NOW(), NOW()),
(11, 'router', 'Bookmark Page', NULL, NULL, 'bookmark.index', 0, 1, NOW(), NOW()),
(12, 'router', 'Media Page', NULL, NULL, 'media.index', 0, 1, NOW(), NOW()),
(13, 'router', 'Documents Page', NULL, NULL, 'document.index', 0, 1, NOW(), NOW()),
(14, 'router', 'Custom Landing Page', NULL, NULL, 'custom_landing_page.index', 0, 1, NOW(), NOW()),
(15, 'router', 'Explore Page', NULL, NULL, 'explore.index', 0, 0, NOW(), NOW()),
(16, 'router', 'Matched Page', NULL, NULL, 'matched.index', 0, 0, NOW(), NOW());


INSERT INTO `{prefix}layout_contents` (`id`, `page_id`, `position`, `type`, `title`, `content`, `enable_title`, `component`, `view_type`, `role_access`, `params`, `order`, `class` ,`created_at`, `updated_at`, `package`) VALUES
(1, 2, 'center', 'component', 'Landing Page Image Block', NULL, 0, 'LandingPageImage', 'desktop', '["all"]' ,'{}',1 ,'Packages\\ShaunSocial\\Core\\Repositories\\Helpers\\Widget\\LandingPageImageWidget' , NOW(), NOW(), 'shaun_core'),
(2, 2, 'right', 'component', 'Login Block', NULL, 0, 'Login', 'desktop', '["all"]' ,'{}', 1,'' ,NOW(), NOW(), 'shaun_core'),
(3, 2, 'center', 'component', 'Login Block', NULL, 0, 'Login', 'mobile', '["all"]' ,'{}', 1,'' ,NOW(), NOW(), 'shaun_core'),
(4, 3, 'center', 'container', 'Container', NULL, 0, 'HomePage', 'desktop', '["all"]' ,'{}', 2,'' ,NOW(), NOW(), 'shaun_core'),
(5, 3, 'center', 'container', 'Container', NULL, 0, 'HomePage', 'mobile', '["all"]' ,'{}', 2,'' ,NOW(), NOW(), 'shaun_core'),
(6, 4, 'center', 'container', 'Container', NULL, 0, 'DiscoveryPage', 'desktop', '["all"]' ,'{}', 1,'' ,NOW(), NOW(), 'shaun_core'),
(7, 4, 'center', 'container', 'Container', NULL, 0, 'DiscoveryPage', 'mobile', '["all"]' ,'{}', 1,'' ,NOW(), NOW(), 'shaun_core'),
(8, 5, 'center', 'container', 'Container', NULL, 0, 'ProfilePage', 'desktop', '["all"]' ,'{}', 1,'' ,NOW(), NOW(), 'shaun_core'),
(9, 5, 'center', 'container', 'Container', NULL, 0, 'ProfilePage', 'mobile', '["all"]' ,'{}', 1,'' ,NOW(), NOW(), 'shaun_core'),
(10, 6, 'center', 'container', 'Container', NULL, 0, 'PostDetailPage', 'desktop', '["all"]' ,'{}', 1,'' ,NOW(), NOW(), 'shaun_core'),
(11, 6, 'center', 'container', 'Container', NULL, 0, 'PostDetailPage', 'mobile', '["all"]' ,'{}', 1,'' ,NOW(), NOW(), 'shaun_core'),
(12, 7, 'center', 'container', 'Container', NULL, 0, 'PageDetail', 'desktop', '["all"]', '{}', 1, 'Packages\\ShaunSocial\\Core\\Repositories\\Helpers\\Container\\PageDetailContainer', NOW(), NOW(), 'shaun_core'),
(13, 7, 'center', 'container', 'Container', NULL, 0, 'PageDetail', 'mobile', '["all"]', '{}', 1, 'Packages\\ShaunSocial\\Core\\Repositories\\Helpers\\Container\\PageDetailContainer', NOW(), NOW(), 'shaun_core'),
(14, 8, 'center', 'container', 'Container', NULL, 0, 'PageDetail', 'desktop', '["all"]', '{}', 1, 'Packages\\ShaunSocial\\Core\\Repositories\\Helpers\\Container\\PageDetailContainer', NOW(), NOW(), 'shaun_core'),
(15, 8, 'center', 'container', 'Container', NULL, 0, 'PageDetail', 'mobile', '["all"]', '{}', 1, 'Packages\\ShaunSocial\\Core\\Repositories\\Helpers\\Container\\PageDetailContainer', NOW(), NOW(), 'shaun_core'),
(16, 9, 'center', 'container', 'Container', NULL, 0, 'PageDetail', 'desktop', '["all"]', '{}', 1, 'Packages\\ShaunSocial\\Core\\Repositories\\Helpers\\Container\\PageDetailContainer', NOW(), NOW(), 'shaun_core'),
(17, 9, 'center', 'container', 'Container', NULL, 0, 'PageDetail', 'mobile', '["all"]', '{}', 1, 'Packages\\ShaunSocial\\Core\\Repositories\\Helpers\\Container\\PageDetailContainer', NOW(), NOW(), 'shaun_core'),
(18, 3, 'right', 'component', 'Suggested Users', NULL, 1, 'UserSuggest', 'desktop', '["all"]' ,'{"item_number":"10"}', 1,'Packages\\ShaunSocial\\Core\\Repositories\\Helpers\\Widget\\UserSuggestWidget' ,NOW(), NOW(), 'shaun_core'),
(19, 3, 'right', 'component', 'Suggested Hashtags', NULL, 1, 'HashtagSuggest', 'desktop', '["all"]' ,'{"item_number":"10"}', 2,'Packages\\ShaunSocial\\Core\\Repositories\\Helpers\\Widget\\HashtagSuggestWidget' ,NOW(), NOW(), 'shaun_core'),
(20, 4, 'right', 'component', 'Trending Users', NULL, 1, 'UserTrending', 'desktop', '["all"]' ,'{"item_number":"10"}', 1,'Packages\\ShaunSocial\\Core\\Repositories\\Helpers\\Widget\\UserTrendingWidget' ,NOW(), NOW(), 'shaun_core'),
(21, 4, 'right', 'component', 'Trending Hashtags', NULL, 1, 'HashtagTrending', 'desktop', '["all"]' ,'{"item_number":"10"}', 2,'Packages\\ShaunSocial\\Core\\Repositories\\Helpers\\Widget\\HashtagTrendingWidget' ,NOW(), NOW(), 'shaun_core'),
(23, 10, 'center', 'container', 'Container', NULL, 0, 'WatchPage', 'desktop', '["all"]' ,'{}', 1,'' ,NOW(), NOW(), 'shaun_core'),
(24, 10, 'center', 'container', 'Container', NULL, 0, 'WatchPage', 'mobile', '["all"]' ,'{}', 1,'' ,NOW(), NOW(), 'shaun_core'),
(25, 10, 'right', 'component', 'Trending Users', NULL, 1, 'UserTrending', 'desktop', '["all"]' ,'{"item_number":"10"}', 1,'Packages\\ShaunSocial\\Core\\Repositories\\Helpers\\Widget\\UserTrendingWidget' ,NOW(), NOW(), 'shaun_core'),
(26, 10, 'right', 'component', 'Trending Hashtags', NULL, 1, 'HashtagTrending', 'desktop', '["all"]' ,'{"item_number":"10"}', 2,'Packages\\ShaunSocial\\Core\\Repositories\\Helpers\\Widget\\HashtagTrendingWidget' ,NOW(), NOW(), 'shaun_core'),
(27, 11, 'center', 'container', 'Container', NULL, 0, 'BookmarkPage', 'desktop', '["all"]' ,'{}', 1,'' ,NOW(), NOW(), 'shaun_core'),
(28, 11, 'center', 'container', 'Container', NULL, 0, 'BookmarkPage', 'mobile', '["all"]' ,'{}', 1,'' ,NOW(), NOW(), 'shaun_core'),
(29, 11, 'right', 'component', 'Trending Users', NULL, 1, 'UserTrending', 'desktop', '["all"]' ,'{"item_number":"10"}', 1,'Packages\\ShaunSocial\\Core\\Repositories\\Helpers\\Widget\\UserTrendingWidget' ,NOW(), NOW(), 'shaun_core'),
(30, 12, 'center', 'container', 'Container', NULL, 0, 'MediaPage', 'desktop', '["all"]' ,'{}', 1,'' ,NOW(), NOW(), 'shaun_core'),
(31, 12, 'center', 'container', 'Container', NULL, 0, 'MediaPage', 'mobile', '["all"]' ,'{}', 1,'' ,NOW(), NOW(), 'shaun_core'),
(32, 5, 'right', 'component', 'Trending Users', NULL, 1, 'UserTrending', 'desktop', '["all"]' ,'{"item_number":"10"}', 1,'Packages\\ShaunSocial\\Core\\Repositories\\Helpers\\Widget\\UserTrendingWidget' ,NOW(), NOW(), 'shaun_core'),
(37, 13, 'center', 'container', 'Container', NULL, 0, 'DocumentsPage', 'desktop', '["all"]' ,'{}', 1,'' ,NOW(), NOW(), 'shaun_core'),
(38, 13, 'center', 'container', 'Container', NULL, 0, 'DocumentsPage', 'mobile', '["all"]' ,'{}', 1,'' ,NOW(), NOW(), 'shaun_core'),
(39, 14, 'center', 'container', 'Container', NULL, 0, 'CustomLandingPage', 'desktop', '["all"]' ,'{}', 2,'' ,NOW(), NOW(), 'shaun_core'),
(40, 14, 'center', 'container', 'Container', NULL, 0, 'CustomLandingPage', 'mobile', '["all"]' ,'{}', 2,'' ,NOW(), NOW(), 'shaun_core'),
(41, 15, 'center', 'container', 'Container', NULL, 0, 'ExplorePage', 'desktop', '["all"]' ,'{}', 1,'' ,NOW(), NOW(), 'shaun_core'),
(42, 15, 'center', 'container', 'Container', NULL, 0, 'ExplorePage', 'mobile', '["all"]' ,'{}', 1,'' ,NOW(), NOW(), 'shaun_core'),
(45, 16, 'center', 'container', 'Container', NULL, 0, 'MatchedPage', 'desktop', '["all"]' ,'{}', 1,'' ,NOW(), NOW(), 'shaun_dating'),
(46, 16, 'center', 'container', 'Container', NULL, 0, 'MatchedPage', 'mobile', '["all"]' ,'{}', 1,'' ,NOW(), NOW(), 'shaun_dating');

INSERT INTO `{prefix}genders` (`id`, `name`, `is_active`, `order`, `created_at`, `updated_at`) VALUES
(1, 'Male', '1', '1', NOW(), NOW()),
(2, 'Female', '1', '2', NOW(), NOW());

INSERT INTO `{prefix}pages` (`id`, `slug`, `role_access`, `content`, `created_at`, `updated_at`) VALUES
(1, 'terms-of-service', '["all"]', '<p>This is the Terms of Service page</p>', NOW(), NOW()),
(2, 'privacy-policy', '["all"]', '<p>This is the Privacy Policy page</p>', NOW(), NOW()),
(3, 'about-us', '["all"]', '<p>This is the About Us page</p>', NOW(), NOW());

INSERT INTO `{prefix}openid_providers` (`id`, `name`, `app_name`, `photo_id`, `photo_default`, `server`, `client_id`, `client_secret`, `scope`, `authorize_endpoint`, `access_token_endpoint`, `get_user_info_endpoint`, `is_active`, `user_id_map`, `email_map`, `name_map`, `avatar_map`, `is_core`, `created_at`, `updated_at`, `order`) VALUES
(1,'Facebook','Facebook',0,'images/default/provider/facebook.png','https://www.facebook.com','','','public_profile email','https://www.facebook.com/dialog/oauth','https://graph.facebook.com/v2.8/oauth/access_token','https://graph.facebook.com/me/?fields=id,name,email,about,picture.type(large)',0,'id','email','name','picture.data.url',1, NOW(), NOW(), '1'),
(2,'Google','Google',0,'images/default/provider/google.png','https://accounts.google.com','','','email profile','https://accounts.google.com/o/oauth2/v2/auth','https://oauth2.googleapis.com/token','https://openidconnect.googleapis.com/v1/userinfo',0,'sub','email','name','picture',1, NOW(), NOW(), '2'),
(3,'Linkedin','Linkedin',0,'images/default/provider/linkedin.png','https://www.linkedin.com/oauth','','','profile email','https://www.linkedin.com/oauth/v2/authorization','https://www.linkedin.com/oauth/v2/accessToken','https://api.linkedin.com/v2/userinfo',0,'sub','email','name','picture',1, NOW(), NOW(), '3'),
(4,'Twitter','Twitter',0,'images/default/provider/twitter.png','https://api.twitter.com/oauth/authenticate','','','tweet.read users.read follows.read follows.write','https://twitter.com/i/oauth2/authorize','https://api.twitter.com/2/oauth2/token','https://api.twitter.com/2/users/me',0,'id','','name',NULL,1, NOW(), NOW(), '4');

INSERT INTO `{prefix}themes` (`id`, `name`, `is_active`, `created_at`, `updated_at`) VALUES
(1, 'Default', '1', NOW(), NOW());

INSERT INTO `{prefix}packages` (`name`, `version`, `created_at`, `updated_at`) VALUES
('shaun_core', '1.5.1', NOW(), NOW());

INSERT INTO `{prefix}currencies` (`code`, `symbol`, `name`, `is_default`, `created_at`, `updated_at`) VALUES
('USD', '$', 'US dollar', 1, NOW(), NOW()),
('EUR', '€', 'Euro', 0, NOW(), NOW()),
('JPY', '¥', 'Japanese yen', 0, NOW(), NOW()),
('GBP', '£', 'British pound sterling', 0, NOW(), NOW()),
('CNY', '¥', 'Chinese yuan', 0, NOW(), NOW()),
('AUD', '$', 'Australian dollar', 0, NOW(), NOW()),
('CAD', '$', 'Canadian dollar', 0, NOW(), NOW()),
('CHF', 'CHF', 'Swiss franc', 0, NOW(), NOW()),
('HKD', '$', 'Hong Kong dollar', 0, NOW(), NOW()),
('NZD', '$', 'New Zealand dollar', 0, NOW(), NOW()),
('VND', '₫', 'Viet Nam dong', 0, NOW(), NOW()),
('SGD', '$', 'Singapore dollar', 0, NOW(), NOW());

INSERT INTO `{prefix}countries` (`id`, `name`, `country_iso`, `state_count`, `order`, `is_active`) VALUES
(1,	'United States',	'US',	51,	231,	1),
(2,	'United Arab Emirates',	'AE',	0,	229,	1),
(3,	'Afghanistan',	'AF',	0,	1,	1),
(4,	'Antigua and Barbuda',	'AG',	0,	10,	1),
(5,	'Anguilla',	'AI',	0,	8,	1),
(6,	'Albania',	'AL',	0,	3,	1),
(7,	'Armenia',	'AM',	0,	12,	1),
(8,	'Netherlands Antilles',	'AN',	0,	155,	1),
(9,	'Angola',	'AO',	0,	7,	1),
(10,	'Antarctica',	'AQ',	0,	9,	1),
(11,	'Argentina',	'AR',	0,	11,	1),
(12,	'American Samoa',	'AS',	0,	5,	1),
(13,	'Austria',	'AT',	0,	15,	1),
(14,	'Australia',	'AU',	0,	14,	1),
(15,	'Aruba',	'AW',	0,	13,	1),
(16,	'Aland Islands',	'AX',	0,	2,	1),
(17,	'Azerbaijan',	'AZ',	0,	16,	1),
(18,	'Bosnia and Herzegovina',	'BA',	0,	28,	1),
(19,	'Barbados',	'BB',	0,	20,	1),
(20,	'Bangladesh',	'BD',	0,	19,	1),
(21,	'Belgium',	'BE',	0,	22,	1),
(22,	'Burkina Faso',	'BF',	0,	35,	1),
(23,	'Bulgaria',	'BG',	0,	34,	1),
(24,	'Bahrain',	'BH',	0,	18,	1),
(25,	'Burundi',	'BI',	0,	36,	1),
(26,	'Benin',	'BJ',	0,	24,	1),
(27,	'Saint Barthelemy',	'BL',	0,	183,	1),
(28,	'Bermuda',	'BM',	0,	25,	1),
(29,	'Brunei Darussalam',	'BN',	0,	33,	1),
(30,	'Bolivia',	'BO',	0,	27,	1),
(31,	'Brazil',	'BR',	0,	31,	1),
(32,	'Bahamas',	'BS',	0,	17,	1),
(33,	'Bhutan',	'BT',	0,	26,	1),
(34,	'Bouvet Island',	'BV',	0,	30,	1),
(35,	'Botswana',	'BW',	0,	29,	1),
(36,	'Belarus',	'BY',	0,	21,	1),
(37,	'Belize',	'BZ',	0,	23,	1),
(38,	'Canada',	'CA',	0,	39,	1),
(39,	'Cocos (Keeling) Islands',	'CC',	0,	47,	1),
(40,	'Congo, the Democratic Republic of the',	'CD',	0,	51,	1),
(41,	'Central African Republic',	'CF',	0,	42,	1),
(42,	'Congo',	'CG',	0,	50,	1),
(43,	'Switzerland',	'CH',	0,	211,	1),
(44,	'Cote D\'Ivoire',	'CI',	0,	54,	1),
(45,	'Cook Islands',	'CK',	0,	52,	1),
(46,	'Chile',	'CL',	0,	44,	1),
(47,	'Cameroon',	'CM',	0,	38,	1),
(48,	'China',	'CN',	0,	45,	1),
(49,	'Colombia',	'CO',	0,	48,	1),
(50,	'Costa Rica',	'CR',	0,	53,	1),
(51,	'Cuba',	'CU',	0,	56,	1),
(52,	'Cape Verde',	'CV',	0,	40,	1),
(53,	'Christmas Island',	'CX',	0,	46,	1),
(54,	'Cyprus',	'CY',	0,	57,	1),
(55,	'Czech Republic',	'CZ',	0,	58,	1),
(56,	'Germany',	'DE',	0,	81,	1),
(57,	'Djibouti',	'DJ',	0,	60,	1),
(58,	'Denmark',	'DK',	0,	59,	1),
(59,	'Dominica',	'DM',	0,	61,	1),
(60,	'Dominican Republic',	'DO',	0,	62,	1),
(61,	'Algeria',	'DZ',	0,	4,	1),
(62,	'Ecuador',	'EC',	0,	63,	1),
(63,	'Estonia',	'EE',	0,	68,	1),
(64,	'Egypt',	'EG',	0,	64,	1),
(65,	'Western Sahara',	'EH',	0,	241,	1),
(66,	'Eritrea',	'ER',	0,	67,	1),
(67,	'Spain',	'ES',	0,	204,	1),
(68,	'Ethiopia',	'ET',	0,	69,	1),
(69,	'Finland',	'FI',	0,	73,	1),
(70,	'Fiji',	'FJ',	0,	72,	1),
(71,	'Falkland Islands (Malvinas)',	'FK',	0,	70,	1),
(72,	'Micronesia, Federated States of',	'FM',	0,	142,	1),
(73,	'Faroe Islands',	'FO',	0,	71,	1),
(74,	'France',	'FR',	0,	74,	1),
(75,	'Gabon',	'GA',	0,	78,	1),
(76,	'United Kingdom',	'GB',	0,	230,	1),
(77,	'Grenada',	'GD',	0,	86,	1),
(78,	'Georgia',	'GE',	0,	80,	1),
(79,	'French Guiana',	'GF',	0,	75,	1),
(80,	'Guernsey',	'GG',	0,	90,	1),
(81,	'Ghana',	'GH',	0,	82,	1),
(82,	'Gibraltar',	'GI',	0,	83,	1),
(83,	'Greenland',	'GL',	0,	85,	1),
(84,	'Gambia',	'GM',	0,	79,	1),
(85,	'Guinea',	'GN',	0,	91,	1),
(86,	'Guadeloupe',	'GP',	0,	87,	1),
(87,	'Equatorial Guinea',	'GQ',	0,	66,	1),
(88,	'Greece',	'GR',	0,	84,	1),
(89,	'South Georgia and the South Sandwich Islands',	'GS',	0,	203,	1),
(90,	'Guatemala',	'GT',	0,	89,	1),
(91,	'Guam',	'GU',	0,	88,	1),
(92,	'Guinea-Bissau',	'GW',	0,	92,	1),
(93,	'Guyana',	'GY',	0,	93,	1),
(94,	'Hong Kong',	'HK',	0,	98,	1),
(95,	'Heard Island and Mcdonald Islands',	'HM',	0,	95,	1),
(96,	'Honduras',	'HN',	0,	97,	1),
(97,	'Croatia',	'HR',	0,	55,	1),
(98,	'Haiti',	'HT',	0,	94,	1),
(99,	'Hungary',	'HU',	0,	99,	1),
(100,	'Indonesia',	'ID',	0,	102,	1),
(101,	'Ireland',	'IE',	0,	105,	1),
(102,	'Israel',	'IL',	0,	107,	1),
(103,	'Isle of Man',	'IM',	0,	106,	1),
(104,	'India',	'IN',	0,	101,	1),
(105,	'British Indian Ocean Territory',	'IO',	0,	32,	1),
(106,	'Iraq',	'IQ',	0,	104,	1),
(107,	'Iran, Islamic Republic of',	'IR',	0,	103,	1),
(108,	'Iceland',	'IS',	0,	100,	1),
(109,	'Italy',	'IT',	0,	108,	1),
(110,	'Jamaica',	'JM',	0,	109,	1),
(111,	'Jordan',	'JO',	0,	111,	1),
(112,	'Japan',	'JP',	0,	110,	1),
(113,	'Kenya',	'KE',	0,	113,	1),
(114,	'Kyrgyzstan',	'KG',	0,	118,	1),
(115,	'Cambodia',	'KH',	0,	37,	1),
(116,	'Kiribati',	'KI',	0,	114,	1),
(117,	'Comoros',	'KM',	0,	49,	1),
(118,	'Saint Kitts and Nevis',	'KN',	0,	185,	1),
(119,	'Korea, Democratic People\'s Republic of',	'KP',	0,	115,	1),
(120,	'Korea, Republic of',	'KR',	0,	116,	1),
(121,	'Kuwait',	'KW',	0,	117,	1),
(122,	'Cayman Islands',	'KY',	0,	41,	1),
(123,	'Kazakhstan',	'KZ',	0,	112,	1),
(124,	'Lao People\'s Democratic Republic',	'LA',	0,	119,	1),
(125,	'Lebanon',	'LB',	0,	121,	1),
(126,	'Saint Lucia',	'LC',	0,	186,	1),
(127,	'Liechtenstein',	'LI',	0,	125,	1),
(128,	'Sri Lanka',	'LK',	0,	205,	1),
(129,	'Liberia',	'LR',	0,	123,	1),
(130,	'Lesotho',	'LS',	0,	122,	1),
(131,	'Lithuania',	'LT',	0,	126,	1),
(132,	'Luxembourg',	'LU',	0,	127,	1),
(133,	'Latvia',	'LV',	0,	120,	1),
(134,	'Libyan Arab Jamahiriya',	'LY',	0,	124,	1),
(135,	'Morocco',	'MA',	0,	148,	1),
(136,	'Monaco',	'MC',	0,	144,	1),
(137,	'Moldova, Republic of',	'MD',	0,	143,	1),
(138,	'Montenegro',	'ME',	0,	146,	1),
(139,	'Madagascar',	'MG',	0,	130,	1),
(140,	'Marshall Islands',	'MH',	0,	136,	1),
(141,	'Macedonia, the Former Yugoslav Republic of',	'MK',	0,	129,	1),
(142,	'Mali',	'ML',	0,	134,	1),
(143,	'Myanmar',	'MM',	0,	150,	1),
(144,	'Mongolia',	'MN',	0,	145,	1),
(145,	'Macao',	'MO',	0,	128,	1),
(146,	'Northern Mariana Islands',	'MP',	0,	163,	1),
(147,	'Martinique',	'MQ',	0,	137,	1),
(148,	'Mauritania',	'MR',	0,	138,	1),
(149,	'Montserrat',	'MS',	0,	147,	1),
(150,	'Malta',	'MT',	0,	135,	1),
(151,	'Mauritius',	'MU',	0,	139,	1),
(152,	'Maldives',	'MV',	0,	133,	1),
(153,	'Malawi',	'MW',	0,	131,	1),
(154,	'Mexico',	'MX',	0,	141,	1),
(155,	'Malaysia',	'MY',	0,	132,	1),
(156,	'Mozambique',	'MZ',	0,	149,	1),
(157,	'Namibia',	'NA',	0,	151,	1),
(158,	'New Caledonia',	'NC',	0,	156,	1),
(159,	'Niger',	'NE',	0,	159,	1),
(160,	'Norfolk Island',	'NF',	0,	162,	1),
(161,	'Nigeria',	'NG',	0,	160,	1),
(162,	'Nicaragua',	'NI',	0,	158,	1),
(163,	'Netherlands',	'NL',	0,	154,	1),
(164,	'Norway',	'NO',	0,	164,	1),
(165,	'Nepal',	'NP',	0,	153,	1),
(166,	'Nauru',	'NR',	0,	152,	1),
(167,	'Niue',	'NU',	0,	161,	1),
(168,	'New Zealand',	'NZ',	0,	157,	1),
(169,	'Oman',	'OM',	0,	165,	1),
(170,	'Panama',	'PA',	0,	169,	1),
(171,	'Peru',	'PE',	0,	172,	1),
(172,	'French Polynesia',	'PF',	0,	76,	1),
(173,	'Papua New Guinea',	'PG',	0,	170,	1),
(174,	'Philippines',	'PH',	0,	173,	1),
(175,	'Pakistan',	'PK',	0,	166,	1),
(176,	'Poland',	'PL',	0,	175,	1),
(177,	'Saint Pierre and Miquelon',	'PM',	0,	187,	1),
(178,	'Pitcairn',	'PN',	0,	174,	1),
(179,	'Puerto Rico',	'PR',	0,	177,	1),
(180,	'Palestinian Territory, Occupied',	'PS',	0,	168,	1),
(181,	'Portugal',	'PT',	0,	176,	1),
(182,	'Palau',	'PW',	0,	167,	1),
(183,	'Paraguay',	'PY',	0,	171,	1),
(184,	'Qatar',	'QA',	0,	178,	1),
(185,	'Reunion',	'RE',	0,	179,	1),
(186,	'Romania',	'RO',	0,	180,	1),
(187,	'Serbia',	'RS',	0,	194,	1),
(188,	'Russian Federation',	'RU',	0,	181,	1),
(189,	'Rwanda',	'RW',	0,	182,	1),
(190,	'Saudi Arabia',	'SA',	0,	192,	1),
(191,	'Solomon Islands',	'SB',	0,	200,	1),
(192,	'Seychelles',	'SC',	0,	195,	1),
(193,	'Sudan',	'SD',	0,	206,	1),
(194,	'Sweden',	'SE',	0,	210,	1),
(195,	'Singapore',	'SG',	0,	197,	1),
(196,	'Saint Helena',	'SH',	0,	184,	1),
(197,	'Slovenia',	'SI',	0,	199,	1),
(198,	'Svalbard and Jan Mayen',	'SJ',	0,	208,	1),
(199,	'Slovakia',	'SK',	0,	198,	1),
(200,	'Sierra Leone',	'SL',	0,	196,	1),
(201,	'San Marino',	'SM',	0,	190,	1),
(202,	'Senegal',	'SN',	0,	193,	1),
(203,	'Somalia',	'SO',	0,	201,	1),
(204,	'Suriname',	'SR',	0,	207,	1),
(205,	'Sao Tome and Principe',	'ST',	0,	191,	1),
(206,	'El Salvador',	'SV',	0,	65,	1),
(207,	'Syrian Arab Republic',	'SY',	0,	212,	1),
(208,	'Swaziland',	'SZ',	0,	209,	1),
(209,	'Turks and Caicos Islands',	'TC',	0,	225,	1),
(210,	'Chad',	'TD',	0,	43,	1),
(211,	'French Southern Territories',	'TF',	0,	77,	1),
(212,	'Togo',	'TG',	0,	218,	1),
(213,	'Thailand',	'TH',	0,	216,	1),
(214,	'Tajikistan',	'TJ',	0,	214,	1),
(215,	'Tokelau',	'TK',	0,	219,	1),
(216,	'Timor-Leste',	'TL',	0,	217,	1),
(217,	'Turkmenistan',	'TM',	0,	224,	1),
(218,	'Tunisia',	'TN',	0,	222,	1),
(219,	'Tonga',	'TO',	0,	220,	1),
(220,	'Turkey',	'TR',	0,	223,	1),
(221,	'Trinidad and Tobago',	'TT',	0,	221,	1),
(222,	'Tuvalu',	'TV',	0,	226,	1),
(223,	'Taiwan, Province of China',	'TW',	0,	213,	1),
(224,	'Tanzania, United Republic of',	'TZ',	0,	215,	1),
(225,	'Ukraine',	'UA',	0,	228,	1),
(226,	'Uganda',	'UG',	0,	227,	1),
(227,	'United States Minor Outlying Islands',	'UM',	0,	232,	1),
(228,	'Andorra',	'AD',	0,	6,	1),
(229,	'Uruguay',	'UY',	0,	233,	1),
(230,	'Uzbekistan',	'UZ',	0,	234,	1),
(231,	'Holy See (Vatican City State)',	'VA',	0,	96,	1),
(232,	'Saint Vincent and the Grenadines',	'VC',	0,	188,	1),
(233,	'Venezuela',	'VE',	0,	236,	1),
(234,	'Virgin Islands, British',	'VG',	0,	238,	1),
(235,	'Virgin Islands, U.s.',	'VI',	0,	239,	1),
(236,	'Viet Nam',	'VN',	0,	237,	1),
(237,	'Vanuatu',	'VU',	0,	235,	1),
(238,	'Wallis and Futuna',	'WF',	0,	240,	1),
(239,	'Samoa',	'WS',	0,	189,	1),
(240,	'Yemen',	'YE',	0,	242,	1),
(241,	'Mayotte',	'YT',	0,	140,	1),
(242,	'South Africa',	'ZA',	0,	202,	1),
(243,	'Zambia',	'ZM',	0,	243,	1),
(244,	'Zimbabwe',	'ZW',	0,	244,	1);

INSERT INTO `{prefix}states` (`id`, `name`, `state_code`, `country_id`, `order`) VALUES
(1, 'Alaska', 'AK', 1, 2),
(2, 'Alabama', 'AL', 1, 1),
(3, 'Arkansas', 'AR', 1, 4),
(4, 'Arizona', 'AZ', 1, 3),
(5, 'California', 'CA', 1, 5),
(6, 'Colorado', 'CO', 1, 6),
(7, 'Connecticut', 'CT', 1, 7),
(8, 'District of Columbia', 'DC', 1, 9),
(9, 'Delaware', 'DE', 1, 8),
(10, 'Florida', 'FL', 1, 10),
(11, 'Georgia', 'GA', 1, 11),
(12, 'Hawaii', 'HI', 1, 12),
(13, 'Iowa', 'IA', 1, 16),
(14, 'Idaho', 'ID', 1, 13),
(15, 'Illinois', 'IL', 1, 14),
(16, 'Indiana', 'IN', 1, 15),
(17, 'Kansas', 'KS', 1, 17),
(18, 'Kentucky', 'KY', 1, 18),
(19, 'Louisiana', 'LA', 1, 19),
(20, 'Massachusetts', 'MA', 1, 22),
(21, 'Maryland', 'MD', 1, 21),
(22, 'Maine', 'ME', 1, 20),
(23, 'Michigan', 'MI', 1, 23),
(24, 'Minnesota', 'MN', 1, 24),
(25, 'Missouri', 'MO', 1, 26),
(26, 'Mississippi', 'MS', 1, 25),
(27, 'Montana', 'MT', 1, 27),
(28, 'North Carolina', 'NC', 1, 34),
(29, 'North Dakota', 'ND', 1, 35),
(30, 'Nebraska', 'NE', 1, 28),
(31, 'New Hampshire', 'NH', 1, 30),
(32, 'New Jersey', 'NJ', 1, 31),
(33, 'New Mexico', 'NM', 1, 32),
(34, 'Nevada', 'NV', 1, 29),
(35, 'New York', 'NY', 1, 33),
(36, 'Ohio', 'OH', 1, 36),
(37, 'Oklahoma', 'OK', 1, 37),
(38, 'Oregon', 'OR', 1, 38),
(39, 'Pennsylvania', 'PA', 1, 39),
(40, 'Rhode Island', 'RI', 1, 40),
(41, 'South Carolina', 'SC', 1, 41),
(42, 'South Dakota', 'SD', 1, 42),
(43, 'Tennessee', 'TN', 1, 43),
(44, 'Texas', 'TX', 1, 44),
(45, 'Utah', 'UT', 1, 45),
(46, 'Virginia', 'VA', 1, 47),
(47, 'Vermont', 'VT', 1, 46),
(48, 'Washington', 'WA', 1, 48),
(49, 'Wisconsin', 'WI', 1, 50),
(50, 'West Virginia', 'WV', 1, 49),
(51, 'Wyoming', 'WY', 1, 51);

INSERT INTO `{prefix}role_permissions` (`role_id`, `permission_id`, `value`) VALUES
(2, 24, '1500'),
(2, 26, '1'),
(2, 27, '5'),
(2, 28, '7'),
(2, 31, '0'),
(2, 32, '0'),
(2, 25, '60');

INSERT INTO `{prefix}content_warning_categories` (`id`, `name`, `is_active`, `is_delete`, `order`, `created_at`, `updated_at`) VALUES
(1, 'Sensitive', 1, 0, 1, NOW(), NOW()),
(2, 'Violence', 1, 0, 2, NOW(), NOW()),
(3, 'Nudity', 1, 0, 3, NOW(), NOW()),
(4, 'Other', 1, 0, 4, NOW(), NOW());

INSERT INTO `{prefix}sms_providers` (`id`, `name`, `class`, `config`, `type`, `is_default`) VALUES
(1, 'Twilio', 'Packages\\ShaunSocial\\Core\\Library\\Sms\\Twilio', '' ,'twilio', 1),
(2, 'Clickatell', 'Packages\\ShaunSocial\\Core\\Library\\Sms\\Clickatell', '' ,'clickatell', 0);

INSERT INTO `{prefix}two_factor_providers` (`id`, `name`, `description` ,`config`, `type`, `is_active`) VALUES
(1, 'Authentication App', 'Get codes from an app like Authy, 1Password, Microsoft, Authenticator, or Google Authenticator.', '', 'auth_app', 0),
(2, 'Sms','Receive a unique code via sms', '','sms', 0),
(3, 'Mail','Receive a unique code via mail', '','mail', 1);

INSERT INTO `{prefix}translations` (`table_name`, `column_name`, `foreign_key`, `locale`, `value`) VALUES
('languages','name',1,'en','English');

INSERT INTO `{prefix}link_icons` (`domain`, `default`, `icon_file_id`, `is_active`) VALUES
('www.facebook.com', 'images/default/link_icon/facebook.svg', 0, true),
('www.linkedin.com', 'images/default/link_icon/linkedin.svg', 0, true),
('x.com', 'images/default/link_icon/x.svg', 0, true),
('www.tiktok.com', 'images/default/link_icon/tiktok.svg', 0, true),
('www.youtube.com', 'images/default/link_icon/youtube.svg', 0, true);

INSERT INTO `{prefix}translate_providers` (`id`, `name`, `class`, `config`, `type`, `is_default`) VALUES
(1, 'Google', 'Packages\\ShaunSocial\\Core\\Library\\Translate\\Google', '' ,'google', 1);